### ISSUE TITLE
Overlapping buttons

### ISSUE THREAD

**Issue by ice051128** [sapondanaisriwan/AdashimaaTube#10]
Is youtube testing their new ui again?
![image](https://user-images.githubusercontent.com/49018832/208232142-65c51b30-9e8c-4400-bc5a-195996be6b41.png)

**Comment by sapondanaisriwan** [comment]
I don't know either but I can't fix it for you since it's not happening to me. 🤔
![image](https://user-images.githubusercontent.com/64634605/208241373-257ef377-8ad9-4757-beea-ec9864d0ade7.png)

**Comment by sapondanaisriwan** [comment]
try this
```
    #contents.ytd-rich-grid-renderer {
        margin-top: 24px !important;
    }
```

**Comment by sapondanaisriwan** [comment]
It has been fixed now
![image](https://user-images.githubusercontent.com/64634605/208242399-fb6c4ece-4648-4b2d-8b05-3f336f5ec7d1.png)

**Comment by ice051128** [comment]
> It has been fixed now ![image](https://user-images.githubusercontent.com/64634605/208242399-fb6c4ece-4648-4b2d-8b05-3f336f5ec7d1.png)

So this actually ended up as the new ui change from youtube?
