### ISSUE TITLE
[Bug]: Unwanted borders around buttons

### ISSUE THREAD

**Issue by ice051128** [sapondanaisriwan/AdashimaaTube#100]
### Describe the bug

There are these borders around the buttons for some reasons

### Screenshots

![image](https://github.com/sapondanaisriwan/AdashimaaTube/assets/49018832/27a75092-08da-44b4-a544-11b0c5e32179)

### What browser are you using?

Microsoft Edge
Version 113.0.1774.35 (Official build) (64-bit)

### What version of AdashimaaTube are you using?

2.2.6

**Comment by sapondanaisriwan** [comment]
Can you send me the link of the that videos?

**Comment by sapondanaisriwan** [comment]
You download other extension so I can't help. https://github.com/sapondanaisriwan/AdashimaaTube/issues/5

**Comment by ice051128** [comment]
> You download other extension so I can't help. #5
> 
> ![image](https://user-images.githubusercontent.com/64634605/237651690-834b3e1a-1d78-43b9-9110-1fcc262ea5b7.png)

What are u even talking about? It's specific to 2.0.6

![image](https://github.com/sapondanaisriwan/AdashimaaTube/assets/49018832/3413057f-fad3-4ef2-bf5e-a1612dba61e2)

**Comment by sapondanaisriwan** [comment]
could you right-click the border area, select "inspect," and send me the screenshots?

**Comment by ice051128** [comment]
> could you right-click the border area, select "inspect," and send me the screenshots?

It was caused by ambient light that overrides the CSS for some reasons, closed
