### ISSUE TITLE
[Feature request]: YouTube has updated its layout for the worse again

### ISSUE THREAD

**Issue by ice051128** [sapondanaisriwan/AdashimaaTube#108]
### Describe the change you'd like

Is it possible to move the filters button to the old place in the middle?

![Screenshot_7](https://github.com/sapondanaisriwan/AdashimaaTube/assets/49018832/c6ffce74-4528-435d-a3ce-2debc24c575b)

**Comment by sapondanaisriwan** [comment]
Yep, it's possible. Looks like you're a tester of a new layout YouTube version.
![msedge_xcYdLQvqTk](https://github.com/sapondanaisriwan/AdashimaaTube/assets/64634605/a97b2299-e6a4-4882-aa78-13fa82fcc010)
