### ISSUE TITLE
[Bug]: Thin Line below the title seperating the description and channel is gone in later version (Doesn't ruin viewing experience)

### ISSUE THREAD

**Issue by Bottomfard6127** [sapondanaisriwan/AdashimaaTube#113]
### Describe the bug

The thin line below the title and other buttons separating the Channel Icon and sub button is gone, it doesn't ruin the viewing experience, but its just uncanny to look at since I got used to it.

### Screenshots

![image](https://github.com/sapondanaisriwan/AdashimaaTube/assets/126884197/abfbed1c-7305-4176-a935-1c73bd955758)
Before
![image](https://github.com/sapondanaisriwan/AdashimaaTube/assets/126884197/24c95103-5245-411d-967b-436565851f37)
After

### What browser are you using?

Firefox version 113.0.2 (64-bit)

### What version of AdashimaaTube are you using?

Last version with the thin line: 2.2.3
Version without the thin line: 2.2.6 beyond

**Comment by Sniperexe** [comment]
another similar issue:
![cf](https://github.com/sapondanaisriwan/AdashimaaTube/assets/97830738/9e03c173-f5bb-44f7-9cf7-3e8d85258e23)

**Comment by sapondanaisriwan** [comment]
> another similar issue:
> 
> ![cf](https://user-images.githubusercontent.com/97830738/242039130-9e03c173-f5bb-44f7-9cf7-3e8d85258e23.PNG)

I have no idea how to fix that yet.
