### ISSUE TITLE
Fix This. Happens in Firefox 86-113

### ISSUE THREAD

**Issue by Denver5280** [sapondanaisriwan/AdashimaaTube#114]
![Capture4784](https://github.com/sapondanaisriwan/AdashimaaTube/assets/131574099/0d61ca91-481a-4303-ab75-e2fed8fa15fc)
Add option to hide likes, subscribe, join
Square mic button, Square Tabs
Replace yoodle with normal youtube logo

**Comment by IdrisQe** [comment]
Use the Legacy version. The new version doesn't function on old Firefox versions.
