### ISSUE TITLE
[Bug]: Shorts displaying in Subscription tab

### ISSUE THREAD

**Issue by goodoria** [sapondanaisriwan/AdashimaaTube#116]
### Describe the bug

Hello i disabled shorts from youtube. however they are showing in the Subscription tab only. Not in search or Home.

![1](https://github.com/sapondanaisriwan/AdashimaaTube/assets/135674914/f5ae427d-ad88-4cd5-ad8f-04bdddf437d4)

Ignore the blank parts as i cropped them out. On the left i have no 'Shorts' tab to click but it still shows.

![2](https://github.com/sapondanaisriwan/AdashimaaTube/assets/135674914/faf6ab25-ad8f-4ffc-81cc-a1755593d63e)

When i click on it, it shows a blank page but the audio is still playing.

Hope it can fixed, thanks.

### What browser are you using?

Chrome Version 114.0.5735.90 (Official Build) (64-bit)

### What version of AdashimaaTube are you using?

v2.2.9

**Comment by sapondanaisriwan** [comment]
Can you right-click around the shorts videos and choose "inspect" and take a screenshot?
![image](https://github.com/sapondanaisriwan/AdashimaaTube/assets/64634605/18b57ffe-df2b-436d-9f86-84296018cb01)

**Comment by goodoria** [comment]
![Untitled](https://github.com/sapondanaisriwan/AdashimaaTube/assets/135674914/f2b93b80-1fb1-4447-9e45-6fb84f8e00a7)

**Comment by sapondanaisriwan** [comment]
@goodoria Can you try this [update](https://github.com/sapondanaisriwan/AdashimaaTube/raw/master/userstyles/AdashimaaTube.user.css)? Please let me know if it works or not.

**Comment by nick-s-b** [comment]
@sapondanaisriwan Hi! I discovered your script just today after YT changed the layout yet again and made it much worse than before! I actually wrote a bunch of  JS user scripts to deal with all these changes but your script is way more comprehensive and looks amazing too.

I came to file the "Shorts showing up" issue as well. I disabled all my scripts and just use yours and it's not hiding the shorts. The only reliable way to hide them is to go hide anything with `ytd-thumbnail-overlay-time-status-renderer[overlay-style="SHORTS"]'` style.

**Comment by sapondanaisriwan** [comment]
> 

I've used that method before, but it came up a new problem: what if the overlay loads slowly? Shorts are not instantly hide.

https://github.com/sapondanaisriwan/AdashimaaTube/assets/64634605/c874779b-a9be-464d-896f-dad9dd8d2ad9

**Comment by nick-s-b** [comment]
@sapondanaisriwan This script works perfectly: https://greasyfork.org/en/scripts/437345-hide-youtube-shorts

**Comment by goodoria** [comment]
> @goodoria Can you try this [update](https://github.com/sapondanaisriwan/AdashimaaTube/raw/master/userstyles/AdashimaaTube.user.css)? Please let me know if it works or not.

unfortunately, still getting shorts

![1](https://github.com/sapondanaisriwan/AdashimaaTube/assets/135674914/53df29e8-e652-444c-a9b8-48d493488e12)

**Comment by sapondanaisriwan** [comment]
Can you provide the screenshot again but you need to expand the code of the shorts element?
![image](https://github.com/sapondanaisriwan/AdashimaaTube/assets/64634605/f521660c-5b6f-42a5-be0f-d69a67fafdd0)

**Comment by sapondanaisriwan** [comment]
@goodoria Can you try the new [update](https://github.com/sapondanaisriwan/AdashimaaTube/raw/master/userstyles/AdashimaaTube.user.css)?

**Comment by sapondanaisriwan** [comment]
Closed since I just got the [new changes](https://[i.imgur.com/YppQnHv.png](https://i.imgur.com/YppQnHv.png)) from YouTube in my test account.
