### ISSUE TITLE
[Bug]: Does not work on Waterfox

### ISSUE THREAD

**Issue by EpicWN1337** [sapondanaisriwan/AdashimaaTube#119]
### Describe the bug

Attempting to go to youtube with the theme enabled on Waterfox results in an error page telling me my browser is outdated, and how to enable layout.css.has-selector.enabled. Waterfox does not have this exact setting, instead having: 
![image](https://github.com/sapondanaisriwan/AdashimaaTube/assets/10932207/f3339096-459a-4c64-b7cb-9702c424a4b3)

### What browser are you using?

Waterfox Version G5.1.8 (64-bit)

**Comment by sapondanaisriwan** [comment]
The `:has()` pseudo class selector was introduced in Firefox 10 but Waterfox is based on Firefox ESR 102 which doesn't have the ability to enable the "has" selector.
