### ISSUE TITLE
Hello! I'm Sam. I absolutely love this project! Not a big fan of the new Youtube layout, so that's why I'm using this, and also because you have your own additions! Furthermore, here's another Idea I'd like to see!

### ISSUE THREAD

**Issue by sapondanaisriwan** [sapondanaisriwan/AdashimaaTube#12]
Hello! I'm Sam. I absolutely love this project! Not a big fan of the new Youtube layout, so that's why I'm using this, and also because you have your own additions! Furthermore, here's another Idea I'd like to see!

(I'm not sure if this is already being worked on!)
(This is a recent change that happened on: I believe around late 2022. And I'm also not sure if this change has rolled out for you guys yet but it has for me.)

Return the Red "HD/4K/8K, etc" icons inside the YouTube quality picker.

Before
<img width="263" alt="Screenshot 2023-01-14 at 20 32 17" src="https://user-images.githubusercontent.com/122677421/212471713-4fe7c76e-5018-4da2-82a7-7292ffb2393f.png">

After
<img width="209" alt="Screenshot 2023-01-14 at 20 24 09" src="https://user-images.githubusercontent.com/122677421/212471709-09d9ecb8-96e3-406d-8a61-8e3c21acd891.png">

Oh, forgot about this.

Before
<img width="198" alt="Screenshot 2023-01-14 at 20 35 05" src="https://user-images.githubusercontent.com/122677421/212471773-83ff906a-a331-4799-bdfc-5c7ac2ea4629.png">

After
<img width="232" alt="Screenshot 2023-01-14 at 20 36 56" src="https://user-images.githubusercontent.com/122677421/212471839-3086bebe-8753-445b-ba1f-52de8445e77e.png">

They added parentheses.

This is an extremely minor request, so you guys don't have to do it! I don't know much about coding so I really don't know how difficult this is to do. But it'd be cool.

_Originally posted by @SamGitHub1807 in https://github.com/sapondanaisriwan/AdashimaaTube/discussions/9#discussioncomment-4684913_

**Comment by sapondanaisriwan** [comment]
Remove parentheses: [e5ad2b8](https://github.com/sapondanaisriwan/AdashimaaTube/commit/e5ad2b8a6bd583097b97f039695c17ec1adfc174)

**Comment by SamGitHub1807** [comment]
Thank you. ❤️ Installing the update right now. You didn't have to do this, but you still did it! I'm sure this wasn't easy to do. 👏 Again, thanks for your efforts!
