### ISSUE TITLE
[Bug]: Hide Shorts

### ISSUE THREAD

**Issue by Bhaalspawn** [sapondanaisriwan/AdashimaaTube#121]
### Describe the bug

it doesn't hide shorts (only "Shorts" on the left menu) in subscriptions page but it hides random videos. I mean now i enabled "hide shorts" and the last video of subiscriptions page is of 2 days ago but it's not the last...

### Screenshots

Default

![shorts](https://github.com/sapondanaisriwan/AdashimaaTube/assets/20135076/311d5290-25db-4ee8-8d6c-e17861d4778c)

Hide Shorts enabled

![hide shorts](https://github.com/sapondanaisriwan/AdashimaaTube/assets/20135076/61d07bd1-6d09-4574-ba55-8132032959c7)

### What browser are you using?

Firefox 114

### What version of AdashimaaTube are you using?

2.3.0

**Comment by sapondanaisriwan** [comment]
Hmmm, I think i already fixed it. Can you reinstall again?
https://github.com/sapondanaisriwan/AdashimaaTube/raw/master/userstyles/AdashimaaTube.user.css

**Comment by sapondanaisriwan** [comment]
After I try on Vivaldi Edge and Firefox. Hide shorts doesn't work on Firefox. weird 
![image](https://github.com/sapondanaisriwan/AdashimaaTube/assets/64634605/eb0ad7dd-f6e2-435d-a468-21f32721068e)

**Comment by sapondanaisriwan** [comment]
Can you try with a different account?

**Comment by Bhaalspawn** [comment]
account of what?

**Comment by sapondanaisriwan** [comment]
I mean can you try logging into a different of YT account? and test it.

**Comment by Bhaalspawn** [comment]
same result...i didn't even know i had a second YT account but i had. it was empty, i subscribed now to some channels and i see shorts

**Comment by sapondanaisriwan** [comment]
https://github.com/sapondanaisriwan/AdashimaaTube/assets/64634605/f9372273-44da-4e48-8c5c-89ae78f0c73e

**Comment by Bhaalspawn** [comment]
it works but it hides shorts even if "hide-shorts" is not enabled

But if i disable and enable Stylus (or your style only) and hide-shorts is disabled..then i see shorts

**Comment by sapondanaisriwan** [comment]
NICE It's just for testing only. I'm going update the style now.

**Comment by sapondanaisriwan** [comment]
Do you find any bugs about shorts other than this?

**Comment by Bhaalspawn** [comment]
not now, but i have another request. i'll open a different issue
