### ISSUE TITLE
[Feature request]: optimization of the occupied space

### ISSUE THREAD

**Issue by Bhaalspawn** [sapondanaisriwan/AdashimaaTube#122]
### Describe the change you'd like

there is a lot unused space at the borders. images eplains better

From this

![Immagine 2023-06-09 185501](https://github.com/sapondanaisriwan/AdashimaaTube/assets/20135076/219c5a2d-8a60-425a-ab98-86c14fe9a42f)

To this

![Immagine 2023-06-09 185501 2](https://github.com/sapondanaisriwan/AdashimaaTube/assets/20135076/465c044e-7e79-4a6a-ae4e-c234a1fe4322)

**Comment by sapondanaisriwan** [comment]
![image](https://github.com/sapondanaisriwan/AdashimaaTube/assets/64634605/3246b467-c052-423a-945c-cac9c8b17ae3)
