### ISSUE TITLE
[Bug]: remove this

### ISSUE THREAD

**Issue by Sniperexe** [sapondanaisriwan/AdashimaaTube#126]
### Describe the bug

Youtube inexplicably decided to have the channel displayed in the description of a video. See photo below for more details, the circled section is what I'd like to see removed

### Screenshots

![4](https://github.com/sapondanaisriwan/AdashimaaTube/assets/97830738/e9e47d4e-1f1a-4b11-9a68-3b3fd6fb5107)

### What browser are you using?

Latest version of Chrome

### What version of AdashimaaTube are you using?

v2.3.1

**Comment by MossyMosMos** [comment]
i was just notice this very recently as well.

**Comment by Sniperexe** [comment]
> Please be polite, It doesn't help to include any profanity, no need for it, it doesn't add any value.

Apologies for my vocabulary, won't be repeated twice.
