### ISSUE TITLE
[Bug]: Subscription feed not showing the most recent videos

### ISSUE THREAD

**Issue by vozKEN** [sapondanaisriwan/AdashimaaTube#127]
### Describe the bug

Cannot see the the most recent videos in my Subscription feed, only videos from e.g. 2 weeks and back.
Refreshing doesn't help.
If I turn AdashimaaTube off, they are displayed.

### What browser are you using?

Mozilla Firefox 114.0.1 (64-bit)

### What version of AdashimaaTube are you using?

v.2.3.0

**Comment by sapondanaisriwan** [comment]
Can you try [v2.3.1](https://userstyles.world/api/style/6944.user.css)?

**Comment by vozKEN** [comment]
Fixed. Thank you.

**Comment by sapondanaisriwan** [comment]
https://github.com/sapondanaisriwan/AdashimaaTube/issues/121
