### ISSUE TITLE
Update ideas, user interface changes + possible bugs that are in need of fixing!

### ISSUE THREAD

**Issue by SamGitHub1807** [sapondanaisriwan/AdashimaaTube#13]
(Sorry if my English is bad, it isn't my native language.)

Minor update ideas and UI fixes for future updates.

UI Request 1: Capitalize the sort by button in the comment section.

The photo below is an archived screenshot of the sort by button on the comment section of YouTube videos before YouTube rolled out the new layout. (taken August 30, 2022)

<img width="233" alt="212627636-03c77a0f-7b58-4155-b560-204de5cf29a3" src="https://user-images.githubusercontent.com/122677421/212684525-76774957-9fa3-4b7a-9d22-555e27cd4eba.png">

Today, this is what the sort by button looks like. [I currently have the style installed but this applies with or without the style installed.] (taken January 16, 2023)

<img width="507" alt="Screenshot 2023-01-16 at 21 03 32" src="https://user-images.githubusercontent.com/122677421/212685602-431815f6-bd19-49fd-8111-c590c885256a.png">

UI Request 2: Spacing adjustments

The "SAVE" button along with the other buttons are slightly moved to the left on videos that cannot be saved to playlists 
(I'm not sure if this is intended, or not and it is a bug.)

For reference:

Video that can't be saved

<img width="1440" alt="212638862-1a9dc3fc-51ab-4e78-831f-08e71900e5d8" src="https://user-images.githubusercontent.com/122677421/212686379-3588d586-a7bf-4fe5-96f2-ed4079d50d0a.png">

Video that can be saved

<img width="1440" alt="212638905-21e437c9-db1c-4b43-8515-74622696dfac" src="https://user-images.githubusercontent.com/122677421/212686544-8305a31a-ef51-4474-a4a1-4528e1e57606.png">

You can also move down the channel logo, subscriber count, name and the subscribe button a little bit!

The photo below is an archived screenshot of YouTube's official layout and spacing

<img width="1440" alt="Screenshot 2023-01-16 at 21 10 33" src="https://user-images.githubusercontent.com/122677421/212685957-34a197c5-6d03-4624-b647-c80d38e2f560.png">

The photo below is what it looks like currently [with the style installed.] You can see that the channel logo, subscriber count, name and the subscribe button are a little bit closer to the border

<img width="1440" alt="Screenshot 2023-01-16 at 21 11 36" src="https://user-images.githubusercontent.com/122677421/212686094-ce00f4eb-e9f7-4536-b9e1-a0350d8889f1.png">

NOTE: This is something nobody should mind as it isn't even that noticeable and necessary lol

If you look closely at both of the photos above, the "SUBSCRIBE" button had some slight roundness but it's barely perceptible!

**Comment by sapondanaisriwan** [comment]
Thanks for some suggestions. Don't worry about your english, I'm not the native-speaker either btw your English is better than me. 😂
Here's the results what I followed your suggestion.

![image](https://user-images.githubusercontent.com/64634605/212819654-72a3b353-9ac8-48c5-a3b6-ea092d7b291c.png)

Youtube for kids.
![image](https://user-images.githubusercontent.com/64634605/212820269-196cc0c4-f490-4b2c-aedc-9f4d73277eba.png)

**Comment by SamGitHub1807** [comment]
> Thanks for some suggestions. Don't worry about your english, I'm not the native-speaker either btw your English is better than me. 😂 Here's the results what I followed your suggestion.
> 
> ![image](https://user-images.githubusercontent.com/64634605/212819654-72a3b353-9ac8-48c5-a3b6-ea092d7b291c.png)
> 
> Youtube for kids. ![image](https://user-images.githubusercontent.com/64634605/212820269-196cc0c4-f490-4b2c-aedc-9f4d73277eba.png)

Wow, a big thank you! I'm grateful for all you do. I hope this projects gets even more recognition and gets even more uses since I recommend it, hehe.
