### ISSUE TITLE
[Bug]: 2 'Subscribed' Buttons in old layout UI

### ISSUE THREAD

**Issue by sliceanddice9** [sapondanaisriwan/AdashimaaTube#132]
### Describe the bug

With the latest [AdashimaaT­ube2.3.2](moz-extension://dd244fbd-065b-4be7-a8b1-e17058330562/edit.html?id=1) there appears to be 2 'Subscribed' buttons. The 'Subscribe' button on the very end when clicked is just the notification bell drop down menu. Having 2 'Subscribed' buttons is redundant IMO.   

### Screenshots

![youtube 2 subscrbe buttons bug](https://github.com/sapondanaisriwan/AdashimaaTube/assets/59092472/02503b06-efea-4186-a13f-db0c1b22f521)

### What browser are you using?

Firefox version 114.0.1

### What version of AdashimaaTube are you using?

v2.3.2

**Comment by sapondanaisriwan** [comment]
🤔
