### ISSUE TITLE
[Bug]: Some buttons' text appears to have a lighter color than in the past

### ISSUE THREAD

**Issue by Sniperexe** [sapondanaisriwan/AdashimaaTube#133]
### Describe the bug

Some buttons have lighter color than they used to, whereas some others have maintained their original

### Screenshots

![35](https://github.com/sapondanaisriwan/AdashimaaTube/assets/97830738/6795c72c-4bfd-4bd4-a520-3cb3362c26c0)

### What browser are you using?

Google Chrome v114.0.5735.134 (Official Build) (64-bit)

### What version of AdashimaaTube are you using?

v2.3.3

**Comment by sapondanaisriwan** [comment]
![image](https://github.com/sapondanaisriwan/AdashimaaTube/assets/64634605/6aaade4b-24c7-4b31-8104-f98b6cba7961)

**Comment by Sniperexe** [comment]
Great
