### ISSUE TITLE
[Feature request]: Return the "Sort by oldest" options

### ISSUE THREAD

**Issue by MossyMosMos** [sapondanaisriwan/AdashimaaTube#134]
### Describe the change you'd like

currently, i just notice that "Sort by oldest" function is missing from our style options now. could you return that option back? as someone like me still interest watching oldest video. @sapondanaisriwan

**Comment by sapondanaisriwan** [comment]
sort by oldest is back now
![image](https://github.com/sapondanaisriwan/AdashimaaTube/assets/64634605/bcc524a8-5f5e-4f01-b997-0324218f614c)
