### ISSUE TITLE
[Feature request]: A way to turn back or turn off youtube handle into the actual usernames

### ISSUE THREAD

**Issue by Bottomfard6127** [sapondanaisriwan/AdashimaaTube#136]
### Describe the change you'd like

A simple feature that could just revert the changes of youtube handles back to usernames of users.

**Comment by sapondanaisriwan** [comment]
Unfortunately, it's impossible to revert it using CSS only. You can install the "[Restore YouTube Username from Handle to Custom](https://greasyfork.org/en/scripts/468740-restore-youtube-username-from-handle-to-custom)" script created by @cyfung1031.
