### ISSUE TITLE
[Feature request]: Auto click through "viewer discretion is advised"

### ISSUE THREAD

**Issue by Cyinthia** [sapondanaisriwan/AdashimaaTube#140]
### Describe the change you'd like

Unlike the mature video warning it is currently impossible to disable this via youtube settings, in song playlists this is absolutely annoying resulting in skipping songs unless you manually click through within a 5 second period. Would something like this be possible?

**Comment by sapondanaisriwan** [comment]
Unfortunately, CSS can't do that it has limited abilities.
