### ISSUE TITLE
[Bug]: wrong links of legacy version

### ISSUE THREAD

**Issue by Kyogre** [sapondanaisriwan/AdashimaaTube#141]
### Describe the bug

In [README.md](https://github.com/sapondanaisriwan/AdashimaaTube#readme) there are two mention of legacy version, but both of them have incorrect link.

1.
> AdashimaaTube-Legacy is suitable for legacy browser. You can install it from [here](https://github.com/sapondanaisriwan/AdashimaaTube/raw/master/AdashimaaTube%20Legacy.user.css).
> 

2.
> If you still prefer to use an old browser, we also have [AdashimaaTube-Legacy](https://github.com/sapondanaisriwan/AdashimaaTube/raw/master/AdashimaaTube%20Legacy.user.css) available.

As I understand, links need to be `https://github.com/sapondanaisriwan/AdashimaaTube/raw/master/userstyles/AdashimaaTube%20Legacy.user.css`

### Screenshots

_Not needed_

### What browser are you using?

Cent Browser 102.0.5005.167

### What version of AdashimaaTube are you using?

-

**Comment by sapondanaisriwan** [comment]
Thank you for telling me
