### ISSUE TITLE
[Bug]: Shorts are grouped at the top in subscriptions

### ISSUE THREAD

**Issue by Usv3re** [sapondanaisriwan/AdashimaaTube#144]
### Describe the bug

So just today this happened to me - and I cannot turn this off. I think it were like that on the main page, but I were able to disable it there. Cannot do the same in subscriptions, I tried all the settings and no result

### Screenshots

![изображение](https://github.com/sapondanaisriwan/AdashimaaTube/assets/137708184/e9d8db4a-4a38-4ad7-8ff6-0adb776d81ab)

### What browser are you using?

Mozilla Firefox 115.0.2 (x64)

### What version of AdashimaaTube are you using?

v2.3.4

**Comment by Usv3re** [comment]
Okay, it's the damned youtube idiots. They added separate line for shorts in subscriptions. Like always, dumbest decision ever

**Comment by Usv3re** [comment]
Damn, appears to be it's the youtube pieces of crap for designers again

**Comment by Usv3re** [comment]
So the damned thing is called shorts shelf and it is soooo irritating. Looking forward to disable shorts shelf in the options, will use another additional style for now

Also you could make an upper left tab for subscription shorts as an option, I think many folks would like that. I certainly would

**Comment by re11ding** [comment]
Using the "Hide shorts" option fixes this, however it would be nice to be able to shrink it down and make it take less space as an alternative option.

**Comment by jenci8888** [comment]
Mine slightly different from your issue, I used 4 styles and 10 tampermonkey. Although, "shorts" on subscription cannot be remove or hide unless if I have to remove shorts via HTML manually. Either, I will look up the latest extension. Used my settings:
![image](https://github.com/sapondanaisriwan/AdashimaaTube/assets/40495799/4561349a-5d88-47de-a614-18ef0f507b19)
![image](https://github.com/sapondanaisriwan/AdashimaaTube/assets/40495799/3c38994c-f2ff-435f-93b1-3a3022d8800e)

![image](https://github.com/sapondanaisriwan/AdashimaaTube/assets/40495799/aa4176d8-577a-4557-8ae4-6ad4095fb630)
![image](https://github.com/sapondanaisriwan/AdashimaaTube/assets/40495799/d7cbb545-8967-455b-ba3c-fe10b23de47e)

**Comment by re11ding** [comment]
The more scripts you have on and the more stylesheets you have active, the higher of a chance that conflicts will occur. I'm more certain this is a conflict issue in your case @jenci8888 

Try disabling everything but AdashimaaTube and then see if the "Remove Shorts" option works.

**Comment by Usv3re** [comment]
> Using the "Hide shorts" option fixes this, however it would be nice to be able to shrink it down and make it take less space as an alternative option.

I don't have that though

**Comment by sapondanaisriwan** [comment]
> "

![image](https://github.com/sapondanaisriwan/AdashimaaTube/assets/64634605/60aabf02-620d-4bf2-986c-80056c5d9fea)

**Comment by sapondanaisriwan** [comment]
If I don't group the shorts shelf or another shelf at the top, it will leave some empty spaces(You can enable the "Layout fix" option to see the problem).

**Comment by re11ding** [comment]
> If I don't group the shorts shelf or another shelf at the top, it will leave some empty spaces(You can disable the "Layout fix" option to see the problem).

Yeah, I noticed that too. There's not much you could do about that either due to the way youtube renders the subscription page either. Maybe you could, but it'd be a ton of unnecessary work when you could just have it at the top. That's why I was saying a thing that makes it smaller would be awesome. Let me see if I can fiddle with the CSS on the main page to create some rules that'll suit that need.

**Comment by sapondanaisriwan** [comment]
It would take too much effort to fix everything with CSS. The best way to fix the issue is to create a new calcElementsPerRow function and replace the one used by YouTube. You can view the source code from [here](https://github.com/sapondanaisriwan/youtube-row-fixer)

**Comment by re11ding** [comment]
No worries, that's fine. It's fine just sitting at the top. I just appreciate that you even allow the modification of the amount of videos displayed on a page for subscriptions to begin with.

**Comment by techgamers2** [comment]
yes shorts were appearing as normal video in subscription page can we get tht back pls

**Comment by re11ding** [comment]
> yes from yesterday shorts are appearing as vertical video in subscription page before it was as normal video thumbnail.. please can we get a feature where shorts appear as normal video thumbnail in subscription page pls

Probably not going to happen as that was a change on Youtube's end, not here. It's way too complicated of a process to get it working like that again.

**Comment by Usv3re** [comment]
> 

Oh thank you! Damn, don't know how I missed this

**Comment by Usv3re** [comment]
> > yes from yesterday shorts are appearing as vertical video in subscription page before it was as normal video thumbnail.. please can we get a feature where shorts appear as normal video thumbnail in subscription page pls
> 
> Probably not going to happen as that was a change on Youtube's end, not here. It's way too complicated of a process to get it working like that again.

What about making a shelf vertical on the side. smth like that?
![3425235423](https://github.com/sapondanaisriwan/AdashimaaTube/assets/137708184/516d5e85-8376-40cd-9158-738e2ed46555)

**Comment by re11ding** [comment]
That's far outside the scope of AdashimaaTube. CSS alone cannot accomplish that. It would have to be an extension/userscript due to having to change the inner structuring of how youtube generates its layout. Worse yet, youtube pages are almost completely generated by a script in of itself, making overriding its generation process far more difficult than one would like. I would know. I originally tried creating a custom script to preserve the old youtube video page layout to give you the same look AdashimaaTube does for video titles and descriptions as a lot of the scripts simply re-enable the dormant HTML google left in there of the old design. Sadly, I was not able to do this as I couldn't inject things correctly. I'm not experienced enough in userscript to make something like you're requesting as a result work.

**Comment by Fred-Vatin** [comment]
If you want to hide it, use this code.
```css
	ytd-browse[page-subtype="subscriptions"] #contents > ytd-rich-section-renderer:nth-of-type(2) {
		display: none !important;
	}
```

**Comment by techgamers2** [comment]
no i dont want to hide my subscription shorts ... i already hide all the other shorts but just need my subscription shorts to be displayed

**Comment by techgamers2** [comment]
> > yes from yesterday shorts are appearing as vertical video in subscription page before it was as normal video thumbnail.. please can we get a feature where shorts appear as normal video thumbnail in subscription page pls
> 
> Probably not going to happen as that was a change on Youtube's end, not here. It's way too complicated of a process to get it working like that again.

ok but if this was possible than it will give me a real reason to use ur userscript coz old ui i can get by just using this [code](https://greasyfork.org/en/scripts/440613-youtube-proper-description/code) on my [enchancer for youtube](https://chrome.google.com/webstore/detail/enhancer-for-youtube/ponfpcnoihfmfllpaingbgckeeldkhle) extension or just putting it in ubo

**Comment by techgamers2** [comment]
> > > yes from yesterday shorts are appearing as vertical video in subscription page before it was as normal video thumbnail.. please can we get a feature where shorts appear as normal video thumbnail in subscription page pls
> > 
> > 
> > Probably not going to happen as that was a change on Youtube's end, not here. It's way too complicated of a process to get it working like that again.
> 
> What about making a shelf vertical on the side? smth like that ![3425235423](https://user-images.githubusercontent.com/137708184/253768086-516d5e85-8376-40cd-9158-738e2ed46555.png)

ya this is pretty good idea if change shorts thumbnail back to normal is not possible

**Comment by techgamers2** [comment]
one thing u can do is try piped extractor to extract youtube thumbnail like piped.video still hav tht layout ( i know its not possible in this project if someone can pls try )
