### ISSUE TITLE
[Feature request]: Seperate Section For 'Shorts Subscriptions' 

### ISSUE THREAD

**Issue by sliceanddice9** [sapondanaisriwan/AdashimaaTube#148]
### Describe the change you'd like

A independent page dedicated to 'Shorts' uploaded from the content creators you are subscribed to  

### Additional context

'Shorts' are great but when there is so many of them they can clutter up the main 'Subscriptions' tab.

**Comment by sapondanaisriwan** [comment]
Unfortunately, it's out of scope of this project.
