### ISSUE TITLE
A way to remove the buttons at the top of the sidebar!

### ISSUE THREAD

**Issue by SamGitHub1807** [sapondanaisriwan/AdashimaaTube#15]
Closed, the issue has been addressed. Thank you!

**Comment by sapondanaisriwan** [comment]
It has that option to remove it already.
![image](https://user-images.githubusercontent.com/64634605/213352296-655829ed-f894-4c71-be60-1ba51937bc42.png)

**Comment by SamGitHub1807** [comment]
> It has that option to remove it already. ![image](https://user-images.githubusercontent.com/64634605/213352296-655829ed-f894-4c71-be60-1ba51937bc42.png)

oops I'm dumb I AM so sorry.
