### ISSUE TITLE
[Bug]: No buttons to sort by popular etc. on channel video pages.

### ISSUE THREAD

**Issue by MrGoatsy** [sapondanaisriwan/AdashimaaTube#151]
### Describe the bug

The bug is described in the title.

**Comment by sapondanaisriwan** [comment]
You need to disable the "Hide tabs" option.
![xEEX94dRLG](https://github.com/sapondanaisriwan/AdashimaaTube/assets/64634605/0f1e7693-2709-4509-8366-e2d994201163)

**Comment by MrGoatsy** [comment]
Weird that it is enabled by default.

Thanks.
