### ISSUE TITLE
[Feature request]: Remove/Hide "Key moments" and  "Chapters" sections in video's page description box after clicked "show more"/"...more"

### ISSUE THREAD

**Issue by MossyMosMos** [sapondanaisriwan/AdashimaaTube#153]
### Describe the change you'd like

(Sorry for reposting to reminds you) i've found the new things since many days ago. the "key moments" and chapters" sections at videos page description box after i clicked "show more" ("...more" for now), and i don't like to see them, could you remove/hide them out? 
Notes: it's was reposted from the previous issue that i posted many days ago (issue #152) @sapondanaisriwan 

![descriptionboxkeymoments](https://github.com/sapondanaisriwan/AdashimaaTube/assets/126743138/c3bed2a1-fcfb-4e20-96f7-5286d52abe3a)

![descriptionboxchapters](https://github.com/sapondanaisriwan/AdashimaaTube/assets/126743138/afd6c900-da9e-4560-8d92-4a9b0e0959bd)

**Comment by sapondanaisriwan** [comment]
duplicate #152
