### ISSUE TITLE
[Bug]: Old Play icons are broken

### ISSUE THREAD

**Issue by MossyMosMos** [sapondanaisriwan/AdashimaaTube#154]
### Describe the bug

i've been recently notice some bugs now. the "old" play icons are become broken now. especially happened with "play all" or sometimes mouse hover over the videos thumbnails etc. could you fix that?

### Screenshots

![playiconchannelpage](https://github.com/sapondanaisriwan/AdashimaaTube/assets/126743138/944496e7-0790-4e68-a37f-3055a7063b2f)

![playiconplaylisthover](https://github.com/sapondanaisriwan/AdashimaaTube/assets/126743138/9a2fdda1-8222-46b8-a4b9-46b6c3044fd6)

![playiconplaylistpage](https://github.com/sapondanaisriwan/AdashimaaTube/assets/126743138/d7b11e1e-d2d6-4f35-9e57-1110b5382cc3)

![playiconhoverthumbnail](https://github.com/sapondanaisriwan/AdashimaaTube/assets/126743138/0e9d10ba-5330-4c60-8a94-9303624c7274)

### What browser are you using?

latest version of browsers

### What version of AdashimaaTube are you using?

v2.3.5

**Comment by sapondanaisriwan** [comment]
Please let me know if v2.3.6 fixed this issue.

**Comment by MossyMosMos** [comment]
> Please let me know if v2.3.6 fixed this issue.

it's fixed now. thanks so much. @sapondanaisriwan
