### ISSUE TITLE
A small bug fix with the "Old Background" option

### ISSUE THREAD

**Issue by SamGitHub1807** [sapondanaisriwan/AdashimaaTube#16]
Hello once more! I haven't mentioned anything the last few days since I've ran out of feature requests due to this project already accomplishing all I needed! 

But anyways, here's a small bug I found with the "Old Background" feature. I turn on the option and the background does not change back to the old background. It was working fine just yesterday. Currently, I don't know if it's just my device or browser.

Here are two screenshots where I had the option turned off and turned on. 

(By the way, I also had the custom appearance section enabled!)

<img width="1440" alt="Screenshot 2023-01-25 at 07 32 20" src="https://user-images.githubusercontent.com/122677421/214445023-6f257b94-3097-42bb-949d-3526ccfda21b.png">
<img width="1440" alt="Screenshot 2023-01-25 at 07 32 27" src="https://user-images.githubusercontent.com/122677421/214445139-8215d8a1-918f-4ca5-a9e7-20fb06b53d8b.png">

I don't know the cause of this, could it be something YouTube changed with the website? You can also see i'm using the latest version as I check for updates frequently.

<img width="1139" alt="image" src="https://user-images.githubusercontent.com/122677421/214487809-15bf59e5-f7f4-4b38-8c3e-bbcf46d95926.png">I just double checked if I was blind and the background does change but I looked up an archive and confirmed it currently doesn't change.

**Comment by sapondanaisriwan** [comment]
Yesterday, I only just realized that something had changed on YouTube again. 🥲

**Comment by SamGitHub1807** [comment]
> Yesterday, I only just realized that something had changed on YouTube again. 🥲

Oh yeah I see, I also experienced it for a short time but then it disappeared.

**Comment by sapondanaisriwan** [comment]
It affected the old playlist also

**Comment by SamGitHub1807** [comment]
> It affected the old playlist also

Oh I see, for me the old playlist works just fine but it could've affected others. Since this is a style, things may break anytime due to YouTube's changes/other reasons.

**Comment by sapondanaisriwan** [comment]
Fixed 
![image](https://user-images.githubusercontent.com/64634605/214559992-6854b534-6856-4c31-b30f-c08012605399.png)

**Comment by SamGitHub1807** [comment]
> Fixed ![image](https://user-images.githubusercontent.com/64634605/214559992-6854b534-6856-4c31-b30f-c08012605399.png)

Thank you for the patches! Much appreciated. ❤️
