### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Sniperexe** [sapondanaisriwan/AdashimaaTube#160]
Do you plan on quitting to update/fix this extension in the near future? Because there's no way I can get used to relatively new UI the youtube has adapted. I'm asking this because I know how it feels to enter the adult life..

**Comment by sliceanddice9** [comment]
Not a fan of the rounded corners on the default video player with the new UI. Hoping an update gives us the option to correct that by reverting it to the old shape.

**Comment by MossyMosMos** [comment]
i don't really like to see anything with rounded corners and their "ugly" new UI things, they are really very ugly to look at.
