### ISSUE TITLE
[Bug]: video's page video box become round + disable fullscreen / exit fullscreen animated icon when mouse hover over the fullscreen / exit fullscreen icon

### ISSUE THREAD

**Issue by MossyMosMos** [sapondanaisriwan/AdashimaaTube#161]
### Describe the bug

i've been found another new ui change to videos page now. video box become round edged instead of straight square and fullscreen / exit fullscreen icons are animated when you hover the mouse over it's icon. could you fix video box into a straight square one and disable the fullscreen / exit fullscreen icons from being animated when mouse hover over it's icon?

### Screenshots

![videopageboxnewui](https://github.com/sapondanaisriwan/AdashimaaTube/assets/126743138/e5e7080a-b853-43cf-9c5d-0d11684ae8a5)

![videopageboxfullscreeniconanimated](https://github.com/sapondanaisriwan/AdashimaaTube/assets/126743138/64f0acf2-b7c0-46a6-9316-4b799ba84b40)

![exitfullscreenanimated](https://github.com/sapondanaisriwan/AdashimaaTube/assets/126743138/f53c63ff-d2dc-404c-9c60-ff9195b46434)

### What browser are you using?

latest version of browsers

### What version of AdashimaaTube are you using?

latest version (v2.3.9)

**Comment by Denver5280** [comment]
Same problem in Firefox and Brave
I did not see it in Vivaldi Chrome and Opera
![Capture4785](https://github.com/sapondanaisriwan/AdashimaaTube/assets/131574099/ed5a2603-1b48-4c50-b9c0-2a65deb071e9)

**Comment by IdleCommentator** [comment]
>I did not see it in Vivaldi Chrome and Opera

It's not really a browser issue - because I have this "Rounded Corners Strike Back" sequel both in Chrome and Edge. It's more like that, as always, they are doing are staggered rollout of the features for different accounts/configs

**Comment by IdleCommentator** [comment]
> To remove the rounded edges from the video player and restore the square shape interface input this code:

This works, thanks ! I wonder if you happen to know how to also "unround" the notifications' box corners ?

**Comment by sliceanddice9** [comment]
The **ytd-watch-flexy[rounded-player-large]:not([fullscreen]):not([theater]) #ytd-player.ytd-watch-flexy { border-radius: 0px; }** filter doesn't seem to work anymore. The latest update does enable you to change the shape of the video player via the 'Boarder' setting, but the 'Boarder' setting also changes the shape of the thumbnails as well. My preference is to keep the thumbnails rounded but keep the video player interface squared. 

Is there a new filter that works like the old filter where the filter ONLY applies independently to the actual video player itself and NOT to the thumbnails?
