### ISSUE TITLE
[Bug]: Video... Title bar? Overlapping Video Player

### ISSUE THREAD

**Issue by CasintheTARDISin221B** [sapondanaisriwan/AdashimaaTube#162]
### Describe the bug

The title bar of videos is overlapping the video player itself, with viewcount and post date displaying over the player. This only seems to occur when specifically the Old Watchpage option is enabled.

### Screenshots

![image](https://github.com/sapondanaisriwan/AdashimaaTube/assets/97483476/3be0e9d1-e1bf-45f3-8a1c-9d06fbf28c52)
![image](https://github.com/sapondanaisriwan/AdashimaaTube/assets/97483476/d779227e-23d6-4f14-b0a9-1a666c344693)

### What browser are you using?

Firefox 116.0.3

### What version of AdashimaaTube are you using?

v2.3.9

**Comment by sapondanaisriwan** [comment]
Can I have the video link?

**Comment by sapondanaisriwan** [comment]
You need to disable the other script.
![image](https://github.com/sapondanaisriwan/AdashimaaTube/assets/64634605/8cfc005e-1a9b-45ac-b117-348e0f8afc59)
