### ISSUE TITLE
[Bug]: Bell Icon is misaligned when subscribed to a channel as well as the name of the channel

### ISSUE THREAD

**Issue by Bottomfard6127** [sapondanaisriwan/AdashimaaTube#163]
### Describe the bug

Bell Icon is under the subscribed button. The name of the channel is also misaligned to when it is subscribed

I think that is all, if its an account based changed, then I am willing to let you borrow my youtube account to fix this.

### Screenshots

screenshot (Before subscribed):
![image](https://github.com/sapondanaisriwan/AdashimaaTube/assets/126884197/8e9d605e-0e8b-49db-8781-2ab123b9a45b)

screenshot (After subscribed):
![image](https://github.com/sapondanaisriwan/AdashimaaTube/assets/126884197/b2cf316a-d06b-4e70-9786-16d36d55bad6)

The channel page is also affected although the name of the channel is not misaligned there even when subscribed

screenshot channel page (Before subscribed):
![image](https://github.com/sapondanaisriwan/AdashimaaTube/assets/126884197/7ea47e63-b7d5-41ad-a250-1b00cb1cbe54)

screenshot channel page (after subscribed):
![image](https://github.com/sapondanaisriwan/AdashimaaTube/assets/126884197/d21f30c6-60c0-480c-aa2c-45390d5f0a20)

Edit: To follow up it is an account based change, since I tested it with a different account with the script on, and the links below the channel is also there but the bell icon is not misaligned.

screenshot main account channel page:
![image](https://github.com/sapondanaisriwan/AdashimaaTube/assets/126884197/3dce9431-3d1c-464f-9bc4-6ef1576c580c)

screenshot other account channel page:
![image](https://github.com/sapondanaisriwan/AdashimaaTube/assets/126884197/5f67f101-6d55-46eb-8250-d968c59fcbdd)

screenshot video player main account:
![image](https://github.com/sapondanaisriwan/AdashimaaTube/assets/126884197/95bb7f30-6225-41bf-a3f2-6b332d220bfc)

screenshot video player other account:
![image](https://github.com/sapondanaisriwan/AdashimaaTube/assets/126884197/8840a639-f143-4483-a007-7fc35f2bab05)

### What browser are you using?

Firefox browser v. 116.0.3 (64-bit)

### What version of AdashimaaTube are you using?

v.2.3.9

**Comment by Bottomfard6127** [comment]
bug is still there even after I tried v2.4.0

**Comment by Bottomfard6127** [comment]
I can let you borrow the youtube account if you want so that you can analyze it much better

**Comment by sapondanaisriwan** [comment]
> I can let you borrow the youtube account if you want so that you can analyze it much better

sure [sapondanaisriwan@gmail.com](mailto:sapondanaisriwan@gmail.com)

**Comment by Bottomfard6127** [comment]
I've sent an email with my gmail account and password, although I might change the password after you find a way to fix it or if you can't fix it now

**Comment by sapondanaisriwan** [comment]
you can change your password now.
