### ISSUE TITLE
[Bug]: After a day, the script hides the video description and the only way to get it back is to uninstall the script

### ISSUE THREAD

**Issue by minou2020** [sapondanaisriwan/AdashimaaTube#165]
### Describe the bug

Title

### What browser are you using?

Microsoft Edge v116 on Windows 11 23H2 v23531

### What version of AdashimaaTube are you using?

Latest, as I got it yesterday from userstyles.world

**Comment by minou2020** [comment]
Edit: it gets working back randomly, then stops working again...

**Comment by sapondanaisriwan** [comment]
can you provide a screenshot?

**Comment by sapondanaisriwan** [comment]
Can you try to disable "Hide game section" option?
![image](https://github.com/sapondanaisriwan/AdashimaaTube/assets/64634605/2b30d9b1-f5ee-493f-93ec-8d6ba028875e)

**Comment by TheMage217** [comment]
Same issue. I reset to default and tested all options, it appears to be "old watch page" causing the issue. It's only occurring for me in once channel, other channels under the same account work fine. Very frustrating.
![broken](https://github.com/sapondanaisriwan/AdashimaaTube/assets/109933722/d38f5914-060e-46fc-9185-608ca718cec7)
![working](https://github.com/sapondanaisriwan/AdashimaaTube/assets/109933722/b8729310-08f0-4af0-a6cb-967cdef74821)

**Comment by WolfRider3000** [comment]
Same here, the description is hidden if the script is on.

With AdashimaaTube:
![Screenshot_832](https://github.com/sapondanaisriwan/AdashimaaTube/assets/67225704/c9051887-74f1-4b1b-aa68-fbfbb575745e)
Without:
![Screenshot_833](https://github.com/sapondanaisriwan/AdashimaaTube/assets/67225704/4e4acf3e-19b1-4d8d-af78-7c11a71d6e32)

**Comment by sapondanaisriwan** [comment]
@WolfRider3000 @minou2020 Please let me know if this works or not.
1. Install [Violentmonkey](https://violentmonkey.github.io/#installation) or [Tampermonkey](https://www.tampermonkey.net/#download) extension.
2. Install [revert-ui-changes.user.js](https://github.com/sapondanaisriwan/AdashimaaTube/raw/master/userscripts/revert-ui-changes.user.js)

**Comment by WolfRider3000** [comment]
It seems to be working. Are you planning to make these changes part of AdashimaaTube or it's only possible with Tampermonkey?

![Screenshot_834](https://github.com/sapondanaisriwan/AdashimaaTube/assets/67225704/acc80cd5-ad15-495d-9a1a-65b31f73d283)

**Comment by sapondanaisriwan** [comment]
> It seems to be working. Are you planning to make these changes part of AdashimaaTube or it's only possible with Tampermonkey?
> 
> ![Screenshot_834](https://user-images.githubusercontent.com/67225704/269053281-acc80cd5-ad15-495d-9a1a-65b31f73d283.png)

It's only possible with Tampermonkey
