### ISSUE TITLE
[Bug]: movie ad that recently appeared on the homepage

### ISSUE THREAD

**Issue by DerFreischutzTKH** [sapondanaisriwan/AdashimaaTube#168]
### Describe the change you'd like

it's really annoying

![ytmovie](https://github.com/sapondanaisriwan/AdashimaaTube/assets/46635684/00d5ab85-5cc4-4435-b063-c18c9df6f2e1)

**Comment by DerFreischutzTKH** [comment]
It seems this bug only happens when I have Stylus or AdashimaaTube enabled.

**Comment by ice051128** [comment]
Have the same issue with movie ads being on homepage

**Comment by sapondanaisriwan** [comment]
Could you right click between the gap of movie ads, select inspect and take a screenshot? like this
![image](https://github.com/sapondanaisriwan/AdashimaaTube/assets/64634605/5851f864-ae00-4f5d-bea3-ca254ff71030)

**Comment by ice051128** [comment]
> Could you right click between the gap of movie ads, select inspect and take a screenshot? like this ![image](https://user-images.githubusercontent.com/64634605/270082774-5851f864-ae00-4f5d-bea3-ca254ff71030.png)

![image](https://github.com/sapondanaisriwan/AdashimaaTube/assets/49018832/9af95a52-5406-4bcd-9ba2-ed24e69dd38a)

**Comment by sapondanaisriwan** [comment]
Can you test my [update](https://github.com/sapondanaisriwan/AdashimaaTube/raw/master/userstyles/AdashimaaTube.user.css)? Is it working or not?

**Comment by ice051128** [comment]
> Can you test my [update](https://github.com/sapondanaisriwan/AdashimaaTube/raw/master/userstyles/AdashimaaTube.user.css)? Is it working or not?

I tried it but there's no option to hide the movie shelf, it's still there

**Comment by sapondanaisriwan** [comment]
Make sure you enable "Home page layout fix" option
![image](https://github.com/sapondanaisriwan/AdashimaaTube/assets/64634605/0f1bd386-5dca-4f0b-8a3d-465cb8292827)

**Comment by DerFreischutzTKH** [comment]
I tested it out for around 10 minutes, and so far I haven't seen the ads bug
Thanks!

**Comment by DerFreischutzTKH** [comment]
After using the new version for a few hours, the ad bug did happen once. I tested it out for 15 minutes, but the bug didn't show up again

**Comment by sapondanaisriwan** [comment]
Can you test the new [update](https://github.com/sapondanaisriwan/AdashimaaTube/raw/master/userstyles/AdashimaaTube.user.css) again?

**Comment by ice051128** [comment]
> @DerFreischutzTKH @ice051128 Can you test the new [update](https://github.com/sapondanaisriwan/AdashimaaTube/raw/master/userstyles/AdashimaaTube.user.css) again?

The movies are still there even with home page and layout fix enabled

**Comment by sapondanaisriwan** [comment]
Can you take a screenshot the entire`ytd-rich-item-rendered` element? thanks
![image](https://github.com/sapondanaisriwan/AdashimaaTube/assets/64634605/d2d499e0-8577-48ce-ab96-9dc57102c1b5)

**Comment by ice051128** [comment]
> Can you take a screenshot the entire`ytd-rich-item-rendered` element? thanks ![image](https://user-images.githubusercontent.com/64634605/270121669-d2d499e0-8577-48ce-ab96-9dc57102c1b5.png)

Like this?
![image](https://github.com/sapondanaisriwan/AdashimaaTube/assets/49018832/0b954cd5-4fa9-4c9d-a299-d96b4652b337)

**Comment by sapondanaisriwan** [comment]
yeah

**Comment by sapondanaisriwan** [comment]
I think this [update](https://github.com/sapondanaisriwan/AdashimaaTube/raw/master/userstyles/AdashimaaTube.user.css) should work

**Comment by ice051128** [comment]
> I think this [update](https://github.com/sapondanaisriwan/AdashimaaTube/raw/master/userstyles/AdashimaaTube.user.css) should work

Can u push this out so I don't need to reinstall the style to try it?

**Comment by sapondanaisriwan** [comment]
Before releasing it, I need to test it. It might have a problem if I release the new changes to everyone.

> > I think this [update](https://github.com/sapondanaisriwan/AdashimaaTube/raw/master/userstyles/AdashimaaTube.user.css) should work
> 
> Can u push this out so I don't need to reinstall the style to try it?

**Comment by DerFreischutzTKH** [comment]
![image](https://github.com/sapondanaisriwan/AdashimaaTube/assets/46635684/52841481-9ab2-45cf-b35f-2378fab117ef)
the update doesn't work

btw
If I turn off AdashimaaTube, I will see a movie section on the homepage
![image](https://github.com/sapondanaisriwan/AdashimaaTube/assets/46635684/013a4bea-6f93-412d-a8c3-977af00738ee)

**Comment by sapondanaisriwan** [comment]
please check the update again

**Comment by sapondanaisriwan** [comment]
If i don't receiving any response, I'll close this issue

**Comment by DerFreischutzTKH** [comment]
It seems the bug has been fixed, I no longer see any movie ads on the new update
Thanks

**Comment by sapondanaisriwan** [comment]
Thank you for replying!
