### ISSUE TITLE
[Bug]: On Unlisted videos,the title and the tags are overlapped

### ISSUE THREAD

**Issue by CatMoon0309** [sapondanaisriwan/AdashimaaTube#169]
### Describe the bug

The title of the video/stream is on top of the tags. I think it's because of the Unlisted text box making the layout wonky.

Video link : https://www.youtube.com/watch?v=dcAE0MeuVM8

### Screenshots

![Screenshot (405)](https://github.com/sapondanaisriwan/AdashimaaTube/assets/82098235/606c4cd7-f114-4a0b-a806-14a2404b2a32)
![Screenshot (406)](https://github.com/sapondanaisriwan/AdashimaaTube/assets/82098235/41e77424-ebbc-475d-97ad-c5ba263374a9)

### What browser are you using?

Brave Version 1.58.131 Chromium: 117.0.5938.92 (Official Build) (64-bit)

### What version of AdashimaaTube are you using?

v2.4.2

**Comment by sapondanaisriwan** [comment]
![image](https://github.com/sapondanaisriwan/AdashimaaTube/assets/64634605/ca38f82e-d771-431b-b3e7-ba6222771c45)
