### ISSUE TITLE
Add support for YouTube Translate button userscript

### ISSUE THREAD

**Issue by xrkaz** [sapondanaisriwan/AdashimaaTube#17]
Hello there! Really liking your YouTube theme :) Would it be possible to add support for this userscript?
As of now, it looks out of place and translation doesn't work for the Description with your theme applied.

There might be issues regarding ordering and importance (stylus applying it's own rules with tampermonkey or greasemonkey applying theirs too, causing conflicts).

https://greasyfork.org/en/scripts/456108

**Comment by sapondanaisriwan** [comment]
Hello, thank you for features you requested. However, the script does not work with the new YouTube UI, so I am unsure of how to fit it into my style. Try to offer some suggestions to the script's owner. If the new YouTube UI issue has been fixed, I probably can combine with my style.

https://user-images.githubusercontent.com/64634605/215425552-003bfa38-2d1a-415f-81f1-ac0a441bb43e.mp4

**Comment by xrkaz** [comment]
Oh, try this: https://www.youtube.com/watch?v=filTeBL7mA0
Maybe there wasn't enough japanese in the description, but it works for me. Even the live chat.

**Comment by sapondanaisriwan** [comment]
It doesn’t work
![image](https://user-images.githubusercontent.com/64634605/215439342-8de73270-8451-4039-be69-d8250c000848.png)

**Comment by xrkaz** [comment]
Hmm, that's strange. :/ I'm 100% certain that it works though. Just tested it in Edge, Chrome, and Firefox. I also tested it in a VM environment, Browserling, works there too. Maybe try running it in a fresh browser?

https://user-images.githubusercontent.com/65538621/215445463-1e7f0f5c-8410-49e8-a501-a20473038e8d.mp4

**Comment by xrkaz** [comment]
I think I found the problem. YouTube has two description panels, is that correct?
You hid #bottom-row in line 1060. That's the panel being targeted by the userscript.
So I guess the description issue can only be fixed by the userscript author.


https://user-images.githubusercontent.com/65538621/215550337-0d6e2da6-df97-451c-bd49-998e5d060900.mp4



However, I fixed the styling of the translate buttons. :)

Here's the code to test it yourself:

```stylus
/* ==UserStyle==
@name           www.youtube.com - 1/30/2023, 11:37:59 PM
@namespace      github.com/openstyles/stylus
@version        1.0.0
@description    A new userstyle
@author         Me
@preprocessor   stylus
@var checkbox test "bottom row" 1
==/UserStyle== */

@-moz-document domain("www.youtube.com")
  
  [name="top_level_translate_btn"] span
    text-transform uppercase
    
  [name="translate_btn"] button
    text-transform uppercase
    color var(--yt-spec-text-secondary) !important
    background transparent !important
  
  if test
    #bottom-row
      display block !important
```

**Comment by sapondanaisriwan** [comment]
Sorry, I can't do with just css. 
https://user-images.githubusercontent.com/64634605/215718637-b851460d-d8e2-4739-bc8a-7ca16d3cfc48.mp4

**Comment by xrkaz** [comment]
> Yes you're right but I can't do with just css.

Yeah, I mentioned that only the userscript author can fix the description issue.
I'll try to contact them to better integrate your theme.

**Comment by sapondanaisriwan** [comment]
Nice btw does my solution work on your end?

> > Yes you're right but I can't do with just css.
> 
> Yeah, I mentioned that only the userscript author can fix the description issue. I'll try to contact them to better integrate your theme.
> 
> https://greasyfork.org/en/scripts/456108-youtube%E8%AF%84%E8%AE%BA%E7%BF%BB%E8%AF%91%E6%8C%89%E9%92%AE/discussions/166771

**Comment by linkwanggo** [comment]
I have read your discussion. I think it is not easy to adapt many different UI, maybe I have to refactor lots of code.
so, what should I do?
I just code JS or write all code to adapt your usersytle?

**Comment by xrkaz** [comment]
> I have read your discussion. I think it is not easy to adapt many different UI, maybe I have to refactor lots of code.
> so, what should I do?
> I just code JS or write all code to adapt your usersytle?

Hey, thanks for responding @linkwanggo. I think you only need to also target the old description panel. No need for rewrite or refactor. As discussed above, YouTube has two description panels, one for the new layout and one for the old layout. Your userscript only targets the description panel within the scope of the new YouTube layout. Any suggestions @sapondanaisriwan?

> Nice btw does my solution work on your end?

I can't make it work now, @linkwanggo just updated it a few hours ago.

**Comment by linkwanggo** [comment]
So how much UI does YouTube have? If I write some code that only works for this userstyle, the code will become more and more confusing.

**Comment by linkwanggo** [comment]
I used to adapt a userstyle, which caused the current code to be a bit confusing.  so I need to be very careful to add some uncommon code.

**Comment by xrkaz** [comment]
What do you mean "How much UI"? Let's wait for @sapondanaisriwan, AFAIK only two, new and old layout. You can probably add comments so the code doesn't become confusing.

**Comment by linkwanggo** [comment]
Maybe "How many"? My English is not good.

**Comment by xrkaz** [comment]
Ah, you mean how many userstyles are there? There's no need to adapt to userstyles at all :D. You just have to add code that also translates the text inside the Description panel used by YouTube's old layout. The panel being targeted at the moment is the Description panel used in the new layout.

**Comment by xrkaz** [comment]
Can you explain to me how the text in the description is translated?

**Comment by linkwanggo** [comment]
The most important thing is to determine the description selector.
It’s okay if only need to adapt to the selector of the new UI and the selector of the old UI, but are there really only these two UIs? 
Is the selector the same for 2021 and 2019?

**Comment by sapondanaisriwan** [comment]
> The most important thing is to determine the description selector. It’s okay if only need to adapt to the selector of the new UI and the selector of the old UI, but are there really only these two UIs? Is the selector the same for 2021 and 2019?

Yes there are only 2 UIs. Youtube display the new UI but hides the old one.
![image](https://user-images.githubusercontent.com/64634605/216044541-4ac2bddf-43d6-4ef5-857a-7e424d544624.png)

![image](https://user-images.githubusercontent.com/64634605/216044597-c0b05e93-01f6-411b-b8cc-2be1824e6f20.png)

**Comment by linkwanggo** [comment]
Is there a general way to determine which UI is in effect?

**Comment by sapondanaisriwan** [comment]
Could you explain in more detail? I'm not sure what you're trying to say.

**Comment by linkwanggo** [comment]
I don't know the old UI at all, it's not clear which parts the script needs to handle...

**Comment by linkwanggo** [comment]
So I just need to judge if the #meta-contents element has a `hidden` attribute?

**Comment by sapondanaisriwan** [comment]
Sorry, I don't know much about JS. Here is the  description selector of the old UI `#content > #description > yt-formatted-string`
![image](https://user-images.githubusercontent.com/64634605/216081412-438b887e-c14f-418f-9a91-28b22ceaf0bc.png)

**Comment by xrkaz** [comment]
Wouldn't it be possible to just target or handle both? @linkwanggo Since the old UI's description will be hidden by default in the new UI. In short, you will be translating both old and new description panels, the other one just won't be displayed.

**Comment by linkwanggo** [comment]
> Wouldn't it be possible to just target or handle both? @linkwanggo Since the old UI's description will be hidden by default in the new UI. In short, you will be translating both old and new description panels, the other one just won't be displayed.

Handling both is the easiest practice， but it is a very bad practice.
I have some ideas already now. If it is effective, I will update.

**Comment by xrkaz** [comment]
Yes, it would be bad practice indeed. There will be a hit in performance. Glad you found a possible solution :D Just do it whenever you can, no rush.

**Comment by sapondanaisriwan** [comment]
Take your time and dont rush 😊

**Comment by linkwanggo** [comment]
I have already updated the script, you can test it.

**Comment by linkwanggo** [comment]
@sapondanaisriwan If you want to combine it better, you need to write some CSS to adapt the style of the button. thank you~

**Comment by sapondanaisriwan** [comment]
> @xrkaz @sapondanaisriwan I have already updated the script, you can test it.

I appreciate your work. Now it's working 😊

https://user-images.githubusercontent.com/64634605/216329480-05f0427c-2c1d-4e2d-b291-76915e684ed7.mp4

**Comment by linkwanggo** [comment]
@sapondanaisriwan Should I add a class tag for dark mode?

**Comment by sapondanaisriwan** [comment]
> @sapondanaisriwan Should I add a class tag for dark mode?

Sure

**Comment by linkwanggo** [comment]
> > @sapondanaisriwan Should I add a class tag for dark mode?
> 
> Sure

OK

**Comment by linkwanggo** [comment]
`div[name="translate_btn"].dark` `div[name="top_level_translate_btn"].dark` for dark mode

**Comment by xrkaz** [comment]
Oh wow! Thanks a lot you two :D @linkwanggo @sapondanaisriwan With teamwork, everything is possible, lol.
