### ISSUE TITLE
[Bug]: Option to hide movie section on homepage not appearing in one of the options in the latest version

### ISSUE THREAD

**Issue by Bottomfard6127** [sapondanaisriwan/AdashimaaTube#170]
### Describe the bug

I don't know if this is a bug or I'm blind but I can't see the hide movie section on homepage option in the latest version of this userstyle. The movie section on homepage appeared to me recently and I don't know how to hide it. 

### Screenshots

Screenshot of the movie section on homepage:

![image](https://github.com/sapondanaisriwan/AdashimaaTube/assets/126884197/fd95b2b9-a5b1-4590-b612-4113cd8569cf)

### What browser are you using?

Firefox Browser v118.0.1 (64-bit)

### What version of AdashimaaTube are you using?

v2.4.3

**Comment by sapondanaisriwan** [comment]
Perhaps I should give it a more clear name. Watch page ->  ? 
![image](https://github.com/sapondanaisriwan/AdashimaaTube/assets/64634605/3aa6c0d8-04b8-4d95-bff9-1bc322dd7b1a)

**Comment by Bottomfard6127** [comment]
Yes I have that turned on but the movie section is still appearing as is in the homepage

**Comment by Bottomfard6127** [comment]
![image](https://github.com/sapondanaisriwan/AdashimaaTube/assets/126884197/b25a5e2f-1677-4854-b8f5-f4147141b55d)

Here is a screenshot for confirmation

**Comment by Bottomfard6127** [comment]
I could once again lend my account to fix this issue much more faster if you wish?

**Comment by sapondanaisriwan** [comment]
> I could once again lend my account to fix this issue much more faster if you wish?

Sure sapondanaisriwan@gmail.com

**Comment by Bottomfard6127** [comment]
> > I could once again lend my account to fix this issue much more faster if you wish?
> 
> Sure [sapondanaisriwan@gmail.com](mailto:sapondanaisriwan@gmail.com)

Email is sent

**Comment by sapondanaisriwan** [comment]
I send your Verify code via email

**Comment by Bottomfard6127** [comment]
Sorry I didn't receive any notifications in my phone. can you please try it again?

**Comment by sapondanaisriwan** [comment]
sure

**Comment by Bottomfard6127** [comment]
hello can you show me again the number in the verification?

**Comment by sapondanaisriwan** [comment]
right now it's 14
![image](https://github.com/sapondanaisriwan/AdashimaaTube/assets/64634605/f39991a2-2eca-4a4b-b189-a823b7a3eb15)

**Comment by sapondanaisriwan** [comment]
Where did you find the movie section? It seems doesn't appear on my end.

**Comment by Bottomfard6127** [comment]
![image](https://github.com/sapondanaisriwan/AdashimaaTube/assets/126884197/a1d79013-e024-4fc5-b199-7b583b01b5cb)
its on this one

**Comment by Bottomfard6127** [comment]
Have you seen it yet? It keeps appearing at the same spot

**Comment by sapondanaisriwan** [comment]
> Have you seen it yet? It keeps appearing at the same spot
No, I haven't. I refresh 3-5 times and keep scrolling down but it's still not appear.

**Comment by Bottomfard6127** [comment]
Can I see the options that you enabled on the userstyles?

**Comment by sapondanaisriwan** [comment]
I disable all style.

**Comment by sapondanaisriwan** [comment]
weird

**Comment by Bottomfard6127** [comment]
hello i noticed something

**Comment by Bottomfard6127** [comment]
when I disabled the movie section there is an X right next to it

**Comment by Bottomfard6127** [comment]
![image](https://github.com/sapondanaisriwan/AdashimaaTube/assets/126884197/a6409f11-fbf5-453b-98ee-7019930898a5)
this one

**Comment by Bottomfard6127** [comment]
but when I enable it the X disappears

**Comment by Bottomfard6127** [comment]
I see

**Comment by Bottomfard6127** [comment]
I've also turned off all of my styles except yours

**Comment by sapondanaisriwan** [comment]
First, right click between the gap of each movie and select "inspect" then right click and select "Expand" then please send the screenshot of html structure
https://github.com/sapondanaisriwan/AdashimaaTube/assets/64634605/72709054-2c90-4e8e-bf24-2509e32d4702

**Comment by Bottomfard6127** [comment]
![image](https://github.com/sapondanaisriwan/AdashimaaTube/assets/126884197/780a54ac-6ae9-4531-b05e-6ad3fd0ca845)
Did I do it right?

**Comment by Bottomfard6127** [comment]
It doesn't have the expand recursively option but it has expand all option

**Comment by sapondanaisriwan** [comment]
> ![image](https://user-images.githubusercontent.com/126884197/272918768-780a54ac-6ae9-4531-b05e-6ad3fd0ca845.png) Did I do it right?

Yes

**Comment by sapondanaisriwan** [comment]
please send me the screenshot again after select "expand all"

**Comment by Bottomfard6127** [comment]
its very long

**Comment by sapondanaisriwan** [comment]
don't worry

**Comment by Bottomfard6127** [comment]
Okay Im going to send parts of it please wait for it. or is it okay if I send a video of me scrolling through the whole html structure?

**Comment by sapondanaisriwan** [comment]
I think send a video is better choice.

**Comment by Bottomfard6127** [comment]
okay wait for a minute

**Comment by Bottomfard6127** [comment]
Hello the video seems to be too large to be sent here, can I send it to you through email?

**Comment by sapondanaisriwan** [comment]
sure

**Comment by Bottomfard6127** [comment]
I've sent it to your email

**Comment by sapondanaisriwan** [comment]
Can you test my update?
https://github.com/sapondanaisriwan/AdashimaaTube/raw/master/userstyles/AdashimaaTube.user.css

**Comment by Bottomfard6127** [comment]
okay

**Comment by sapondanaisriwan** [comment]
please let me know if it works or not

**Comment by sapondanaisriwan** [comment]
Have you enabled "hide movie section"?

**Comment by Bottomfard6127** [comment]
yes

**Comment by sapondanaisriwan** [comment]
is it still appear?

**Comment by Bottomfard6127** [comment]
It doesn't appear when I disable the layout fix on homepage

**Comment by Bottomfard6127** [comment]
![image](https://github.com/sapondanaisriwan/AdashimaaTube/assets/126884197/05dfc9e4-4058-4ee7-a969-83ac3a2f5fcd)
this one

**Comment by Bottomfard6127** [comment]
but when I enable the layout fix it shows up again similar to the one in my first screenshot

**Comment by sapondanaisriwan** [comment]
omg what happened 😢

**Comment by Bottomfard6127** [comment]
maybe I can inspect again but with the layout fix

**Comment by sapondanaisriwan** [comment]
is "Hide movie section" working for you?

**Comment by Bottomfard6127** [comment]
yes

**Comment by sapondanaisriwan** [comment]
nice

**Comment by Bottomfard6127** [comment]
> but when I enable the layout fix it shows up again similar to the one in my first screenshot

its just this is the new problem now

**Comment by Bottomfard6127** [comment]
maybe it is browser type of problem?

**Comment by sapondanaisriwan** [comment]
nope

**Comment by sapondanaisriwan** [comment]
please test my update again
https://github.com/sapondanaisriwan/AdashimaaTube/raw/master/userstyles/AdashimaaTube.user.css

**Comment by Bottomfard6127** [comment]
OMG IT FIXED THE ISSUE!

**Comment by sapondanaisriwan** [comment]
FINALLY

**Comment by Bottomfard6127** [comment]
Thank you so much, truly! you are a life saver <3 Sorry for this long and grueling task

**Comment by sapondanaisriwan** [comment]
No problem :)

**Comment by sapondanaisriwan** [comment]
don't forget to change your YT password
