### ISSUE TITLE
[Bug]: profile description not show

### ISSUE THREAD

**Issue by peatzaza** [sapondanaisriwan/AdashimaaTube#176]
### Describe the bug

profile description not show
subscribe button is in steaming sentence

### Screenshots

![Screenshot_15](https://github.com/sapondanaisriwan/AdashimaaTube/assets/149168801/71f9f48c-ba89-4b81-97df-1638fa71d776)

### What browser are you using?

Yandex browser Version 23.9.2.888 (64-bit)

### What version of AdashimaaTube are you using?

v.2.4.4

**Comment by NinjaBlazin** [comment]
Same here, description box is completely gone. Can't expand it at all.

**Comment by peatzaza** [comment]
ผมเพิ่งรู้ว่าคนทำส่วนขยายนี้เป็นคนไทย

**Comment by sapondanaisriwan** [comment]
> ไทย

มาช่วยทำได้นะครับ ติดสอบมหาลัยอยู่ ไม่ว่างทำ

**Comment by peatzaza** [comment]
เออ ทำไม่เป็นครับ-_-

**Comment by sapondanaisriwan** [comment]
ไปโหลดแค่ revert-ui-change.js พอละครับ ถ้าจะแก้หน้างาน 
https://github.com/sapondanaisriwan/AdashimaaTube#-installation
![image](https://github.com/sapondanaisriwan/AdashimaaTube/assets/64634605/6d6de422-32f7-46b2-9f8d-c57c406b2d4a)

**Comment by peatzaza** [comment]
จู่ๆ ปุ่มกลับเป็นปกติเลยครับ

**Comment by peatzaza** [comment]
แล้วพอรีเฟรชอีกรอบก็กลับมาบัคอีกรอบ

**Comment by sapondanaisriwan** [comment]
> ไปโหลดแค่ revert-ui-change.js พอละครับ ถ้าจะแก้หน้างาน https://github.com/sapondanaisriwan/AdashimaaTube#-installation ![image](https://private-user-images.githubusercontent.com/64634605/278848293-6d6de422-32f7-46b2-9f8d-c57c406b2d4a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzOTA5NDMsIm5iZiI6MTcwNTM5MDY0MywicGF0aCI6Ii82NDYzNDYwNS8yNzg4NDgyOTMtNmQ2ZGU0MjItMzJmNy00NmIyLTlmOGQtYzU3YzQwNmIyZDRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE2VDA3MzcyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFjMmVjZGFmYWM2NTI0NzAyMzczYWUwODdkZWQzNmYxY2NjYTRlYjg3NjYxZTk0MWQ5NTUzM2Q5MTQyZTVmZTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gFWz2WkC4mbNNG4Nj22mfw76N656DaXKjFlada8eGsU)

ทำตามที่บอกได้เลยนะคับผม
