### ISSUE TITLE
[Feature request]: Option to revert the buttons

### ISSUE THREAD

**Issue by SeedTechMC** [sapondanaisriwan/AdashimaaTube#178]
### Describe the change you'd like

In the latest UI update by YouTube, they made it so that the buttons are like this across the screen:
![Screenshot 2023-10-27 at 14 01 55](https://github.com/sapondanaisriwan/AdashimaaTube/assets/86826014/daa19240-99ea-4601-8d51-56638410796d)

I'd like to be able to revert this to how the buttons were before, as it really messed with my mussile memory, and I have issues finding studio.

**Comment by sapondanaisriwan** [comment]
Please see https://github.com/sapondanaisriwan/AdashimaaTube?tab=readme-ov-file#-installation

![image](https://github.com/sapondanaisriwan/AdashimaaTube/assets/64634605/1bc6ec90-1737-4a25-9ede-a95f9ea3b494)
