### ISSUE TITLE
More update ideas! (to enhance some features)

### ISSUE THREAD

**Issue by SamGitHub1807** [sapondanaisriwan/AdashimaaTube#18]
Hey, this is Sam again, I was amazed to see what the three of you worked on for the "translate function"; it was true collaboration lol. I'm back with more update ideas to improve one feature that this style currently offers!

How to improve the consistency of the "Hide Channel Handle" features!

This is a current screenshot of the YouTube channels that pop up when you search for them. 
It would be cool if channel handles were also hidden here, but that would probably be hard to do.

<img width="844" alt="Screenshot 2023-02-05 at 09 27 13" src="https://user-images.githubusercontent.com/122677421/216796944-f02dc300-bbe8-438e-9f55-891e70166708.png">

Here is a screenshot of YouTube on June 13, 2022 when the old YouTube interface was still present:

<img width="896" alt="Screenshot 2023-02-05 at 09 34 23" src="https://user-images.githubusercontent.com/122677421/216797119-06ba723a-c4a6-458d-a4b2-38f65766eff1.png">

As you can see the channel handles are gone. 

(I think this will be extremely hard to do, just based on the circumstances lol)

Taps Roundness

Here's a current screenshot of the YouTube homepage. 

<img width="1440" alt="Screenshot 2023-02-05 at 13 54 58" src="https://user-images.githubusercontent.com/122677421/216804206-9c514217-b791-4b0b-9edb-b76fe42c8387.png">

Here's a screenshot of the YouTube homepage on July 7, 2022 when the old YouTube interface was still present:

<img width="1440" alt="Screenshot 2023-02-05 at 13 55 11" src="https://user-images.githubusercontent.com/122677421/216804254-78fbd20c-dc16-414e-aaa4-7eb6d3fa99a0.png">

As you can observe the taps roundness changed a bit.

That's all!

**Comment by sapondanaisriwan** [comment]
Unfortunately,I can't bring the videos count back because YouTube removed it from the search page except the channel page.

**Comment by SamGitHub1807** [comment]
> Unfortunately,I can't bring the videos count back because YouTube removed it from the search page except the channel page.

Noted on this one, thank you for informing me! I'll remove that request and replace it with a minor one.

**Comment by SamGitHub1807** [comment]
Thank you. ❤️

**Comment by SamGitHub1807** [comment]
Hello! It turns out I missed one more area where channel handles appear. It's when you search up for a music artist, I'm not sure if there's more areas where channel handles appear but when I do come across one, I'll be sure to inform you!

Present-day screenshot (with style applied)
<img width="1440" alt="Screenshot 2023-02-06 at 13 55 39" src="https://user-images.githubusercontent.com/122677421/216894498-056ad244-58d3-4bdb-b53d-4cc84405a4d9.png">

Old screenshot (August 1, 2022)
![Uploading Screenshot 2023-02-06 at 13.55.07.png…]()


That's all!

**Comment by sapondanaisriwan** [comment]
I appreciate you letting me know, but I have some bad news: I don't have a premium account, and that channel handles can't be removed using only CSS. Maybe in the future I'll create my own extension without some limitations like these lol.

**Comment by SamGitHub1807** [comment]
Ah okay haha, appreciate you for letting me know as well. I wasn't aware that it required premium to download, but now I do. Looking forward to your projects in the future too! I'll close this issue now @

**Comment by sapondanaisriwan** [comment]
I just borrow my friend account

**Comment by SamGitHub1807** [comment]
Ah, I see. If you still need me the steps to reproduce the bgus, I'm not good at these things haha but I can try, I'm not sure how to though.

**Comment by sapondanaisriwan** [comment]
As you can see It still works on my side
![image](https://user-images.githubusercontent.com/64634605/216962815-9193596b-9b31-409b-879a-02e98b8fac0c.png)

**Comment by SamGitHub1807** [comment]
Oh I see, if you're online, the bug won't be visible (example below)
<img width="1440" alt="Screenshot 2023-02-06 at 19 46 41" src="https://user-images.githubusercontent.com/122677421/216963533-a109f1d5-0cd7-457b-bb26-bf5415e8a879.png">

But if you completely go offline, like turn off the internet, and go to your downloads then watch a downloaded video, you can see the bug. I think this isn't possible to fix haha.
<img width="1440" alt="Screenshot 2023-02-06 at 19 47 13" src="https://user-images.githubusercontent.com/122677421/216963671-23db3e1e-2a81-44fe-a669-d721b265be6c.png">

**Comment by sapondanaisriwan** [comment]
Fixed :)
![image](https://user-images.githubusercontent.com/64634605/216971906-7e8b6692-4068-4f3b-9abe-b0e39b516e81.png)

**Comment by SamGitHub1807** [comment]
Wow awesome! Thank you so much ❤️, I appreciate it. I thought it was hard to fix lol, but again, anything is possible!
