### ISSUE TITLE
Bug fixes! (I think it will be a little difficult to patch)

### ISSUE THREAD

**Issue by SamGitHub1807** [sapondanaisriwan/AdashimaaTube#19]
Hey, Sam here again! This is slightly difficult for me to explain lol, and I apologize if it's hard to understand. But anyways, a change that YouTube made a while ago affected the hashtags on YouTube videos making them completely invisible. (if the style is applied)

If you don't have the style applied, and go to a video that's currently trending, you'll see that YouTube recently changed the position of all the "hashtags." It's placed beside the view count and upload date of videos. 

I'll turn off anti-shorts for now and I'll use this shorts video as an example lol. As you can see, #36 on trending.
<img width="318" alt="image" src="https://user-images.githubusercontent.com/122677421/218296762-d1c207b6-aad1-41c6-986f-32b7d74babb7.png">

Previously, these "hashtags" would be above the title. 

Now, I have the style applied, and I am not able to see the "#36 on trending" above the title.
<img width="482" alt="image" src="https://user-images.githubusercontent.com/122677421/218296789-4190df13-2280-40b8-8628-f9a1393b8089.png">

Sorry if this is difficult to understand... but that's all.
You don't have to do this. This is a minor change and this bug does not affect the viewing experience, just thought I'd let you know!

**Comment by sapondanaisriwan** [comment]
Fixed :)
![image](https://user-images.githubusercontent.com/64634605/218442161-8a45d49d-06a3-4627-93d7-71d1a3e1cb62.png)

**Comment by SamGitHub1807** [comment]
Awesome! Thank you :D
