### ISSUE TITLE
9 grid YouTube apps icon

### ISSUE THREAD

**Issue by Techfromthepast123** [sapondanaisriwan/AdashimaaTube#20]
<img width="614" alt="Screen-Shot-2021-06-19-at-2 43 18-PM" src="https://user-images.githubusercontent.com/112059671/219071332-4a703bf2-7bac-4345-a94b-c601c0dcd5b1.png">
Recently,YouTube put the  Youtube tv,kids and studio app links in the sidebar as of August of 2022 and before that there was a 9 grid app icon in the top navigation bar where the profile and notifications are located and it would open a menu that showed the YouTube apps like YouTube Music,YouTube TV,YouTube kids link.
Can you add it in the next update ?

**Comment by sapondanaisriwan** [comment]
Unfortunately, I can't bring it back. 🥲

**Comment by Techfromthepast123** [comment]
Its fine,I understand.
Creating an extra menu for youtube's top bar will be difficult
