### ISSUE TITLE
More ideas for Adashimaatube

### ISSUE THREAD

**Issue by Techfromthepast123** [sapondanaisriwan/AdashimaaTube#21]
1.Compact search bar:
https://userstyles.world/style/4663/restore-youtube-search-box-to-compact
2.Old video unavailable page:
https://greasyfork.org/en/scripts/443404-restore-classic-video-unavailable-page
3.Old youtube notification badge style:
https://userstyles.world/style/4674/youtube-revert-old-notification-badge
4.Compact thumbnails on search results:
https://userstyles.world/style/5544/restore-compact-thumbnails-search-page-on-youtube
5.Watch9 reconstruct (restore the watch page layout from 2017-2019) compatibility:
https://github.com/aubymori/Watch9Reconstruct/
This is not an idea but a bug with the old icons
On the sidebar,when a category is selected,the icon is black instead of red.
If these could be added/fixed,it would be cool!!!

**Comment by sapondanaisriwan** [comment]
Thank you for your idea, but I think that's good enough right now. In the upcoming update, I'll removing the old icons option because I find it difficult to me to find all of the old icons and there are some restrictions that can't be fixed with CSS alone.

**Comment by Techfromthepast123** [comment]
I found a script that restores old icons and it restores almost every old icon including YouTube shorts:
https://greasyfork.org/en/scripts/454534-youtube-old-icons-restorer

**Comment by Techfromthepast123** [comment]
Maybe you could add it since it has all the old icons in  it

**Comment by sapondanaisriwan** [comment]
> I found a script that restores old icons and it restores almost every old icon including YouTube shorts: https://greasyfork.org/en/scripts/454534-youtube-old-icons-restorer

Thanks please give me some time

**Comment by Techfromthepast123** [comment]
Okay take your time

**Comment by sapondanaisriwan** [comment]
Have you got a screenshot when you selected category then the icon turned red?

**Comment by Techfromthepast123** [comment]
Yes,Here are the screenshots

AdashimaaTube with old icons applied:
![Capture d'écran_20230219_064442](https://user-images.githubusercontent.com/112059671/219931379-694a4227-c22e-45bb-af70-a5e4442886de.png)

Old YouTube screenshot (Wayback Machine Archive from February 2021):
![Capture d'écran_20230219_064510](https://user-images.githubusercontent.com/112059671/219931397-5a3e4735-31dd-43bc-b64b-4de783f3e1c6.png)

**Comment by Techfromthepast123** [comment]
Also I noticed,In AdashimaaTube,the size of the sidebar buttons size is off a bit.

**Comment by sapondanaisriwan** [comment]
Fixed in v1.8.9 and add more the old icons
![msedge_iHDt9c4RSm](https://user-images.githubusercontent.com/64634605/219947932-42ca92e2-c2cb-4f5f-b6d3-6a8b1118f67c.png)
