### ISSUE TITLE
Small bug fixes

### ISSUE THREAD

**Issue by SamGitHub1807** [sapondanaisriwan/AdashimaaTube#22]
Hey, Sam here once again! Just here to report a few bugs so they may be fixed!

1: Spacing for dislike count.

<img width="577" alt="Screenshot 2023-02-21 at 08 04 46" src="https://user-images.githubusercontent.com/122677421/220215463-daa4c020-bb9b-4433-8fb7-a219316308b8.png">

Recently, RYD updated (version 3.0.0.8) and they stated "multiple annoying bugs fixed." Two of which are the spacing of dislike counts, and If I'm not mistaken, the ratio bar randomly disappearing. 

<img width="151" alt="image" src="https://user-images.githubusercontent.com/122677421/220215624-91a6fbeb-532b-4409-b335-5d8c59f254dc.png">

As you can see, I have no styles currently applied, and they did indeed fix the spacing and ratio bar.

<img width="379" alt="image" src="https://user-images.githubusercontent.com/122677421/220216134-e1605379-11c1-4ad1-b220-fdebc4bbcbcb.png">

And now, I have the style applied and the spacing is now a bit off.

2: Display Dislike Text feature
 
<img width="220" alt="Screenshot 2023-02-21 at 08 07 49" src="https://user-images.githubusercontent.com/122677421/220215704-e75111e0-f812-4c99-a6a6-21432a26b49c.png">

If you turn on this option with the Return YouTube Dislike extension installed, this will be the result:
<img width="197" alt="image" src="https://user-images.githubusercontent.com/122677421/220215794-2266054b-9067-4417-9b7f-c98fad52f57f.png">

But if you uninstall or turn off Return YouTube Dislike, the feature works fine.
<img width="132" alt="image" src="https://user-images.githubusercontent.com/122677421/220215874-9e536c5d-3877-46ed-beb7-de6d560f5b92.png">

The bug is that, with the extension, it displays the current dislike count but also still displays the DISLIKE text, rather than not displaying the DISLIKE text at all (like in previous versions).

That's all!

**Comment by sapondanaisriwan** [comment]
I got it. I'll fix it right away since I just got home.

**Comment by sapondanaisriwan** [comment]
Fixed in v1.9.0 :)

**Comment by SamGitHub1807** [comment]
> Fixed in v1.9.0 :)

Thank you! ❤️
