### ISSUE TITLE
Got duplicate video and channel when the "Search Result In A Grid" option was turn on.

### ISSUE THREAD

**Issue by sapondanaisriwan** [sapondanaisriwan/AdashimaaTube#23]
I have no idea how to fix these bugs yet 🫠

Steps to reproduce the problem.
1. Scroll quickly to the bottom of the page. 
2. Re-do step 1 until you get the duplicate video and channel.

![msedge_l81pKBx5ya](https://user-images.githubusercontent.com/64634605/220691164-4813505d-f0a7-4599-991d-317c621924c2.png)

https://imgur.com/dnFr43e

**Comment by sapondanaisriwan** [comment]
I think this is a bug of YouTube.

**Comment by NickDaSniper** [comment]
It's a bug of youtube, got double videos on my homepage while using the mobile app, it's youtube's problem.
