### ISSUE TITLE
End screen videos

### ISSUE THREAD

**Issue by NickDaSniper** [sapondanaisriwan/AdashimaaTube#24]
This might sound a bit of impossible to accomplish but I would like a feature that removes the videos(and other things) displayed in the end of a video. To better understand what I'm saying I'll attach a photo.
![ewf](https://user-images.githubusercontent.com/97830738/221383080-e89e5ef5-0a26-4993-ae2a-def52caf4d3e.PNG)

**Comment by sapondanaisriwan** [comment]
Did you miss this option?
![pAoVufrtJn](https://user-images.githubusercontent.com/64634605/221391687-228a82a2-e64c-40fd-9e7f-100ccc4692f2.png)

**Comment by NickDaSniper** [comment]
my bad, didn't know what that meant to do until now, thanks❤
