### ISSUE TITLE
Incorrect spacing between watch page buttons

### ISSUE THREAD

**Issue by PANMARSAG14** [sapondanaisriwan/AdashimaaTube#25]
![chrome_27pKhFyagH](https://user-images.githubusercontent.com/81510862/221409555-237ad9ab-5f73-4dd9-a026-995fb57343fe.png)
It should look like this:
![chrome_q2LF3JYqRk](https://user-images.githubusercontent.com/81510862/221409561-2b7f0a0a-7839-4327-9a0d-f632c3e785f9.png)

**Comment by sapondanaisriwan** [comment]
give me some time please

**Comment by sapondanaisriwan** [comment]
This, ok? @PANMARSAG14
![msedge_xE6NnhmOOX](https://user-images.githubusercontent.com/64634605/221618529-96825e7f-b480-47c8-a267-d970266b61ef.png)

**Comment by PANMARSAG14** [comment]
Yes.

**Comment by sapondanaisriwan** [comment]
Fixed in v1.9.6
