### ISSUE TITLE
Some suggestion and issues to fix

### ISSUE THREAD

**Issue by sapondanaisriwan** [sapondanaisriwan/AdashimaaTube#27]
Hey! Sam again, this time I made a discussion for something since I think it would be difficult to achieve, so I won't even make an issue hahaha. Anyways! With the new v1.9.5 update that fixed the overlapping elements (**yes, I waited for this update haha since if you corrected the spacing, it would cause issues, specifically for those with smaller screen resolutions**). Anyways, continuing, do you think it's possible to change the spacing of the watch page buttons to reflect YouTube's official spacing? Here are some photos:

YouTube's official spacing (October 1, 2021):

<img width="324" alt="Screenshot 2023-02-27 at 07 02 15" src="https://user-images.githubusercontent.com/122677421/221442868-61cc7862-0e97-4bac-adbc-132290a2401c.png">

The style:
<img width="317" alt="Screenshot 2023-02-27 at 06 52 34" src="https://user-images.githubusercontent.com/122677421/221442874-7b3d648f-69f0-4392-bf4b-7fcc39337a51.png">

Here's another official YouTube layout screenshot, but this time it's when they added the clip, download, etc, buttons lol. 
<img width="869" alt="image" src="https://user-images.githubusercontent.com/122677421/221442927-66aa0cbb-e2aa-4706-b50d-2031296d2cc0.png">

If you do this you'd also have to change the length of the ratio-bar because of the spacing as seen in the previous 2 screenshots That's why I thought it'd be hard to achieve. A similar issue by @ PANMARSAG14 was made before this, I just thought I'd give more information and also add that the like and dislike button also had incorrect spacing. 

Also since I'm doing this discussion, I might as well put really minor changes and fixes here instead of making a new issue. 

1: This drop-down menu when you click the three dots and the quality picker had a little bit of roundness, until YouTube's new layout that made it more round lol.
<img width="174" alt="image" src="https://user-images.githubusercontent.com/122677421/221491969-3658ba65-c558-400c-9998-455b6948729a.png">
<img width="648" alt="image" src="https://user-images.githubusercontent.com/122677421/221443409-5b0f7e35-f305-4eb5-84b0-c357de0f71bb.png">

2: The hashtags above the title fix changed the spacing a bit, so now, even videos without hashtags have an empty space where the hashtags would be.

Videos without hashtags:

YouTube's official spacing:
<img width="230" alt="image" src="https://user-images.githubusercontent.com/122677421/221491466-1729400b-f0b4-43a6-b918-5005434ff727.png">

The style:
<img width="296" alt="image" src="https://user-images.githubusercontent.com/122677421/221490630-78ab2b32-8bc7-482e-be09-1041915f7ad0.png">

Videos with hashtags:

YouTube's official spacing:
<img width="206" alt="image" src="https://user-images.githubusercontent.com/122677421/221490449-74a4b70a-be5c-4f96-afec-29b7fbacbf66.png">

The style:
<img width="283" alt="image" src="https://user-images.githubusercontent.com/122677421/221490393-67f92826-f04a-46ae-b5e9-d63085ee7c5b.png">

More suggestions that I think are hard/impossible to achieve:

If you observe the ratio bar, it had no roundness. (by the way this was YouTube's official ratio bar not Return YouTube Dislike!)
Another thing is that, the ratio bar was closer to the border line, I think it's actually on top of the border line.

That's all and thank you!

_Originally posted by @SamGitHub1807 in https://github.com/sapondanaisriwan/AdashimaaTube/discussions/9#discussioncomment-5116817_

**Comment by sapondanaisriwan** [comment]
This, ok?
![msedge_xE6NnhmOOX](https://user-images.githubusercontent.com/64634605/221618529-96825e7f-b480-47c8-a267-d970266b61ef.png)

**Comment by SamGitHub1807** [comment]
It’s perfect! Sorry I wasn’t able to reply fast due to time zones… wow… and you also did everything I said, thank you so so much! That was very much not needed but that’s so amazing and kind of you. That was a lot of work. I apologize!

**Comment by sapondanaisriwan** [comment]
Fixed in v1.9.6

**Comment by SamGitHub1807** [comment]
Thank you very much! I know this was a lot, so thank you; I don't know how else to express my gratitude other than to say thank you haha. And it was nice of you to even follow the smallest of my requests! ❤️

**Comment by sapondanaisriwan** [comment]
No problem :)
