### ISSUE TITLE
Is this theme compatible with YouTube Redux ?

### ISSUE THREAD

**Issue by Techfromthepast123** [sapondanaisriwan/AdashimaaTube#29]
Is AdashimaaTube compatible with youtube redux because without adashimaatube,youtube redux still has 2023 elements and I want to bring back some of the 2021 elements to youtube redux.

**Comment by sapondanaisriwan** [comment]
I'm not quite sure because I never use Adashimaatube and YouTube redux together. Anyway, if you still want to bring back some of elements in 2021. You can create a new userstyles and make it compatible with YouTube Redux, by copying and pasting some of the CSS that you wish to bring it back.
