### ISSUE TITLE
My Youtube's search bar won't become square edged + home page and channel page options are missing after i updated style.

### ISSUE THREAD

**Issue by MossyMosMos** [sapondanaisriwan/AdashimaaTube#30]
i don't know how could i turn youtube's search bar into square edged instead of being round?

an issue what i got
<img width="948" alt="ytsearchbar round" src="https://user-images.githubusercontent.com/126743138/222330136-2ab30736-c991-4bf3-9110-143ad66ad65f.png">

I want something like this
<img width="464" alt="youtubesearchbar square" src="https://user-images.githubusercontent.com/126743138/222326670-a7e5f168-acb6-4817-9619-f73af3f3b501.png">

also when i install this style it still won't let my youtube's search bar to become a square edged  too. i don't know if they were bugged or something? even if i put border radius into 0px it still won't change my youtube's search bar into square to me.

**Comment by sapondanaisriwan** [comment]
It seems Youtube update their UI again. I'll fix in the next update

**Comment by SamGitHub1807** [comment]
> It seems Youtube update their UI again. I'll fix in the next update

Thank you! It also happens to me, just earlier this day my search bar was square edged but then suddenly it became round lol.

Also seems like the ui on the videos page on channels got updated

Before: 

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/122677421/222337054-e3108a1d-a484-4cfe-8dc4-cd90e69bf7b0.png">

After:

<img width="1440" alt="Screenshot 2023-03-02 at 13 12 52" src="https://user-images.githubusercontent.com/122677421/222337084-f7c16e85-bc72-4a4d-b36c-4ccdde52c771.png">

So now, with the style installed, it looks like this:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/122677421/222336833-b208502d-a760-42d8-8449-379c87a8a851.png">

**Comment by sapondanaisriwan** [comment]
Pray for Youtube to stop updating their ui 😂.

**Comment by SamGitHub1807** [comment]
Hey! @sapondanaisriwan. Yes it works now. 

Search bar:
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/122677421/222447480-dd03111c-fe66-4fc5-9a70-78965da6e207.png">

Channel page:
<img width="1440" alt="Screenshot 2023-03-02 at 21 53 37" src="https://user-images.githubusercontent.com/122677421/222447805-1f8a2611-1a1a-4633-bff9-249778e029eb.png">

Thank you! :)

**Comment by MossyMosMos** [comment]
now my search bar is finally turned into square. but now settings for home pages and channel pages are missing like sort oldest in channel pages.

**Comment by sapondanaisriwan** [comment]
I removed it because it's not useful. I'll include it in the upcoming update if you really want it.

**Comment by MossyMosMos** [comment]
since i loved to watch an old videos i would like to have it back.

**Comment by sapondanaisriwan** [comment]
what about other features that i removed? do you want to bring it back?

**Comment by MossyMosMos** [comment]
yes, i really want to bring back removed features too.

**Comment by sapondanaisriwan** [comment]
Yep, Hide shorts and Anti-shorts is the same things. I just changed the name to make it easy to understand.

**Comment by MossyMosMos** [comment]
> now my search bar is finally turned into square. but now settings for home page and channel page options are missing like "sort by oldest" in channel page etc.
> 
> before updated style 
> 
> <img alt="adashimatube196" width="240" src="https://user-images.githubusercontent.com/126743138/222592661-e105b368-2d63-40c2-a691-6f6e6d16e89d.png">
> 
> after updated style
> 
> <img alt="adashimatube197" width="240" src="https://user-images.githubusercontent.com/126743138/222592831-c4723ce6-08d8-4260-9d63-4157196b1830.png">

so you gonna add these options back in the next update right?

**Comment by sapondanaisriwan** [comment]
Yeah, but not right now I'm out side

**Comment by SamGitHub1807** [comment]
Thanks for the new update and patches! Yep, just noticed YouTube changed their UI again lol. Also, happy to see my language is included when displaying dislike text

**Comment by NickDaSniper** [comment]
got same problem here, rounded search box..

**Comment by MossyMosMos** [comment]
Thank you so much for adding these options back after i updated style.

**Comment by MossyMosMos** [comment]
> got same problem here, rounded search box..

i think the search bar should be square in the latest style update.

**Comment by NickDaSniper** [comment]
My bad, I just found out how to update it - was using v 1.6.9 till today as
I thought it automatically gets updated.
Though I have a request. I noticed with the newest version a few features
have been removed (probably in this whole meantime), and I think I'd prefer
sticking to the older (I did export it thankfully before updating). Yet in
the latest version there are some features (ex. old button icons) that I'd
love to use. Is there any way to copy paste the specific code so as to have
both new and old features at once? Like copy a part of the new script
(1.9.9) and paste it to the old script (1.6.9). If you could give me a
video how to do it so as not to miss anything or mess up, it would be much
appreciated (1 example is enough to follow and do the rest).
Again you're a legend, I'm the type of people whom nostalgia hits them bad
and that's why I love your stylus. I'm not really keen to changes, maybe
that's another factor. Regardless if you could provide me with help or not,
thank you very much for doing this whole thing.

Στις Σάβ, 4 Μαρ 2023, 01:45 ο χρήστης MossyMosMos ***@***.***>
έγραψε:
