### ISSUE TITLE
French translation for dislike text option

### ISSUE THREAD

**Issue by Techfromthepast123** [sapondanaisriwan/AdashimaaTube#33]
The french translation of the dislike text is "Je n'aime pas"

**Comment by sapondanaisriwan** [comment]
Added in v1.9.9 [`5713f1e`](https://github.com/sapondanaisriwan/AdashimaaTube/commit/5713f1efcf6f5e5ae0a28fe5e01a889950ef9aa4)
![OZuotAAdvA](https://user-images.githubusercontent.com/64634605/222877448-f65b2c7f-6802-4d94-bdb9-962d8a475e04.png)
