### ISSUE TITLE
AdashimaaTube latest update removed the option to hide handles

### ISSUE THREAD

**Issue by Techfromthepast123** [sapondanaisriwan/AdashimaaTube#34]
Can you add back the options to hide channel handles because in the latest update,that option got removed

**Comment by sapondanaisriwan** [comment]
Yes, of course.

**Comment by sapondanaisriwan** [comment]
Bring it back in v1.9.9 [`5713f1e`](https://github.com/sapondanaisriwan/AdashimaaTube/commit/5713f1efcf6f5e5ae0a28fe5e01a889950ef9aa4)
![u0G2VJI17t](https://user-images.githubusercontent.com/64634605/222877548-7d9917ca-cfce-4237-a81b-e3aa0f142160.png)
