### ISSUE TITLE
I'll stop updating my styles

### ISSUE THREAD

**Issue by sapondanaisriwan** [sapondanaisriwan/AdashimaaTube#35]
I'll stop updating my styles until Youtube stop update their UI (Yesterday I wasted my time to fix the UI issues on the videos page on channels but today it was fixed?????????????)

Maybe Youtube decides which feature gets removed and the other decides how many users it affects

?
![image](https://user-images.githubusercontent.com/64634605/222877743-a728875b-72a2-4fd3-81be-9869c73db45f.png)

??
![image](https://user-images.githubusercontent.com/64634605/222877800-ae345013-9672-4665-8dc1-4d2807345d57.png)
![image](https://user-images.githubusercontent.com/64634605/222877808-37a018e6-c7cb-4a0a-8879-727df31093d7.png)

???
![image](https://user-images.githubusercontent.com/64634605/222877843-7bced227-738c-405a-b253-43dbb8a88af8.png)

**Comment by SamGitHub1807** [comment]
Indeed, I have also noticed all of these new changes. We understand. There will be adjustments because of the new changes on YouTube. Luckily I haven't experienced these all in my main account yet. But I have in my other accounts.

**Comment by NickDaSniper** [comment]
Understandable. You may update them less frequently, such as every month or so. Your work so far is very much appreciated!

**Comment by MossyMosMos** [comment]
Don't be hard on yourself. I understand it may took a time to figure out about fixing some certain UI or other stuffs. but I really appreciated to your hard work.

**Comment by Techfromthepast123** [comment]
I found a userstyle CSS that reverts this channel page update that you're talking about,maybe you could add it in AdashimaaTube:https://userstyles.world/style/8808/youtube-old-channel-page

**Comment by NickDaSniper** [comment]
Just letting you know in the most recent update (2.0.1) the channel icon is showing round (when being on the channel page) despite having set it to 0% roundness. Yet what surprised me the most, is that such problem is not seen in the version 1.6.9. Keep in mind to encompass this fix in your next update, thanks.

**Comment by sapondanaisriwan** [comment]
> Just letting you know in the most recent update (2.0.1) the channel icon is showing round (when being on the channel page) despite having set it to 0% roundness. Yet what surprised me the most, is that such problem is not seen in the version 1.6.9. Keep in mind to encompass this fix in your next update, thanks.

Can you provide the screenshot please?

**Comment by Sniperexe** [comment]
> > Just letting you know in the most recent update (2.0.1) the channel icon is showing round (when being on the channel page) despite having set it to 0% roundness. Yet what surprised me the most, is that such problem is not seen in the version 1.6.9. Keep in mind to encompass this fix in your next update, thanks.
> 
> Can you provide the screenshot please?

sure, here you go.
![yeahh](https://user-images.githubusercontent.com/97830738/223470353-af6bf1c6-bd0d-4897-9f4d-5472baa33b24.PNG)

**Comment by sapondanaisriwan** [comment]
I'll continue except YouTube push the stupid update that waste my time.

**Comment by DAOWAce** [comment]
Speaking of updates, yeah, Youtube updated on my end recently.

Now the videos on the home page no longer show the play popup and instead play in place (even smaller!) and when mousing over ANY part of the 'tile' so to speak.  What an awful change.

And to make things worse, the video player page keeps scrolling back up to the top when looking at/making a comment.  This is infuriating.

Why do they keep doing this?  Seriously who is asking for all these stupid changes?
