### ISSUE TITLE
Something seriously  wrong with style. Please fix it

### ISSUE THREAD

**Issue by rakitanc** [sapondanaisriwan/AdashimaaTube#36]
![Screenshot from 2023-03-07 01-41-21](https://user-images.githubusercontent.com/64612555/223219860-826ccde5-05b6-4a66-8412-4e9eab623a7a.png)

This is showing up on youtube homepage

**Comment by TsukiKatana** [comment]
I faced the same issue too.

**Comment by katsura9000** [comment]
> what browser are you using and what version?
> 
> The error page is designed specifically for Firefox users. I made that decision because if you don't have the most recent version of browser, several settings won't work such as Hide shorts, Hide buttons, display dislike text, etc.

I'm using vivaldi browser (latest version and it's based on chromium) and i also face the same issue.

**Comment by sapondanaisriwan** [comment]
> > what browser are you using and what version?
> > The error page is designed specifically for Firefox users. I made that decision because if you don't have the most recent version of browser, several settings won't work such as Hide shorts, Hide buttons, display dislike text, etc.
> 
> I'm using vivaldi browser (latest version and it's based on chromium) and i also face the same issue.

Are you sure?
![vivaldi_bz8Q9LhMlA](https://user-images.githubusercontent.com/64634605/223324004-08c0b453-ebea-476d-b149-68530f26f430.png)

**Comment by Ii-xD-iI** [comment]
> what browser are you using and what version?
> 
> The error page is designed specifically for Firefox users. I made that decision because if you don't have the most recent version of browser, several settings won't work such as Hide shorts, Hide buttons, display dislike text, etc.

that's the sketchiest way to do it imo

**Comment by katsura9000** [comment]
> > > what browser are you using and what version?
> > > The error page is designed specifically for Firefox users. I made that decision because if you don't have the most recent version of browser, several settings won't work such as Hide shorts, Hide buttons, display dislike text, etc.
> > 
> > 
> > I'm using vivaldi browser (latest version and it's based on chromium) and i also face the same issue.
> 
> Are you sure? ![vivaldi_bz8Q9LhMlA](https://user-images.githubusercontent.com/64634605/223324004-08c0b453-ebea-476d-b149-68530f26f430.png)

vivaldi provided an update ,i updated the browser now the issue is fixed.

**Comment by sapondanaisriwan** [comment]
> > > > what browser are you using and what version?
> > > > The error page is designed specifically for Firefox users. I made that decision because if you don't have the most recent version of browser, several settings won't work such as Hide shorts, Hide buttons, display dislike text, etc.
> > > 
> > > 
> > > I'm using vivaldi browser (latest version and it's based on chromium) and i also face the same issue.
> > 
> > 
> > Are you sure? ![vivaldi_bz8Q9LhMlA](https://user-images.githubusercontent.com/64634605/223324004-08c0b453-ebea-476d-b149-68530f26f430.png)
> 
> vivaldi provided an update ,i updated the browser now the issue is fixed. what is the toggle "hide channel profile" for ? i am curious since i can't see any change when i turn it on.

You must first enable "Video Appearance" before it will work properly.
![W2erW53ZS6](https://user-images.githubusercontent.com/64634605/223360172-7f30012a-79cb-410a-b6bb-822e165c5c9d.png)

**Comment by sapondanaisriwan** [comment]
> > > > > > what browser are you using and what version?
> > > > > > The error page is designed specifically for Firefox users. I made that decision because if you don't have the most recent version of browser, several settings won't work such as Hide shorts, Hide buttons, display dislike text, etc.
> > > > > 
> > > > > 
> > > > > I'm using vivaldi browser (latest version and it's based on chromium) and i also face the same issue.
> > > > 
> > > > 
> > > > Are you sure? ![vivaldi_bz8Q9LhMlA](https://user-images.githubusercontent.com/64634605/223324004-08c0b453-ebea-476d-b149-68530f26f430.png)
> > > 
> > > 
> > > vivaldi provided an update ,i updated the browser now the issue is fixed. what is the toggle "hide channel profile" for ? i am curious since i can't see any change when i turn it on.
> > 
> > 
> > You must first enable "Video Appearance" before it will work properly. ![W2erW53ZS6](https://user-images.githubusercontent.com/64634605/223360172-7f30012a-79cb-410a-b6bb-822e165c5c9d.png)
> 
> "video appearance" is enabled i still can't see what "hide channel profile" does.

We can create a new discussion

**Comment by sapondanaisriwan** [comment]
Please follow the instructions: [What should I do if I receive an error page and why?](https://github.com/sapondanaisriwan/AdashimaaTube#-what-should-i-do-if-i-receive-an-error-page-and-why)
