### ISSUE TITLE
what is the toggle "hide channel profile" for ? i am curious since i can't see any change when i turn it on.

### ISSUE THREAD

**Issue by sapondanaisriwan** [sapondanaisriwan/AdashimaaTube#37]
vivaldi provided an update ,i updated the browser now the issue is fixed.
what is the toggle "hide channel profile" for ? i am curious since i can't see any change when i turn it on.

_Originally posted by @katsura9000 in https://github.com/sapondanaisriwan/AdashimaaTube/issues/36#issuecomment-1457701426_

**Comment by sapondanaisriwan** [comment]
@katsura9000 Can you provide me a full screenshot?

**Comment by katsura9000** [comment]
> @katsura9000 Can you provide me a full screenshot?

i figured it out . hide channel profile toggle hides profile pics of youtubers on home page.

**Comment by sapondanaisriwan** [comment]
Yeah
