### ISSUE TITLE
The Channel profile is showing round

### ISSUE THREAD

**Issue by sapondanaisriwan** [sapondanaisriwan/AdashimaaTube#38]
Just letting you know in the most recent update (2.0.1) the channel icon is showing round (when being on the channel page) despite having set it to 0% roundness. Yet what surprised me the most, is that such problem is not seen in the version 1.6.9. Keep in mind to encompass this fix in your next update, thanks.

![yeahh](https://user-images.githubusercontent.com/97830738/223470353-af6bf1c6-bd0d-4897-9f4d-5472baa33b24.PNG)

_Originally posted by @Sniperexe in https://github.com/sapondanaisriwan/AdashimaaTube/issues/35#issuecomment-1458379263_

**Comment by sapondanaisriwan** [comment]
@Sniperexe It's working on my end. Maybe you receive the new update from YouTube so I can't do anything about that
![msedge_XAhKMSD0uw](https://user-images.githubusercontent.com/64634605/223474011-39f4c925-70c4-4158-be81-62c3a18d39fe.png)

**Comment by Sniperexe** [comment]
ok so I just uninstalled and re-installed chrome and now everything seems to be working fine. For now. ;)

**Comment by sapondanaisriwan** [comment]
I'm glad to hear that
