### ISSUE TITLE
[New UI] Video/Shorts/Live page has a bigger font size

### ISSUE THREAD

**Issue by Youtubepls** [sapondanaisriwan/AdashimaaTube#48]
Hi,

first of all: great work, Youtube is much better witch your userstyle. Thanks a lot!

Today I noticed that the font on the video/Shorts/Live page suddenly has a different size. It's a little bit bigger than before and bigger than on the home page. I upgraded from v1.9.7 to v2.0.5, but I can't find a way to bring the font back to the size of the home page. Any idea of how I can fix that?

![bigger font](https://user-images.githubusercontent.com/127688486/224565461-d2a70cb4-8149-46a8-984a-bbe6cfa10313.PNG)

**Comment by sapondanaisriwan** [comment]
Did you accidentally increase the font size? YouTube uses a 10px font size as its default.
![0k9MlFMV5r](https://user-images.githubusercontent.com/64634605/224614860-00bbb3b3-0623-42da-adce-25d77e52a755.png)

**Comment by Youtubepls** [comment]
No, it is at 10px, but it has no effect on these pages. I should better say: I can increase the font with this slider, but at 10px the font size on these pages is still bigger than normal.

**Comment by sapondanaisriwan** [comment]
Did you zoom in the page?

**Comment by sapondanaisriwan** [comment]
I can't see any changes on my end.

**Comment by Youtubepls** [comment]
Yes, but  it's zoomed to 90%, because the side bar isn't showing up at 100% zoom. But it's the same problem at 100% zoom:

![bigger font 2](https://user-images.githubusercontent.com/127688486/224659490-485409c0-d18e-4f6e-9cbd-155d8f3dcf6e.PNG)

**Comment by sapondanaisriwan** [comment]
you're saying that text will be small at 90% zoom, but large at 100%. right?

**Comment by Youtubepls** [comment]
Nope, the text on Videos/Shorts/Live is always bigger than on Home. No matter if 90% or 100% zoom.

**Comment by sapondanaisriwan** [comment]
Can you send me the link? I'll check

**Comment by Youtubepls** [comment]
The link to the channel page? Well, it's the same problem on any channel pages^^

https://www.youtube.com/@pcd

**Comment by sapondanaisriwan** [comment]
You're right. It's bigger than usual.

My main account the font size is at 14px.
![f3QiP9pPqz](https://user-images.githubusercontent.com/64634605/224665154-4aedcca7-f59a-4d46-870d-1028d0cd52d1.png)


My test account on the home tap font size is at 14px but on videos tap is at 16px.
![2ItxtHQk6J](https://user-images.githubusercontent.com/64634605/224666053-25b88236-794c-48a3-8ccd-4f126d52b76e.png)

**Comment by sapondanaisriwan** [comment]
@Youtubepls You can install the update from [here](https://github.com/sapondanaisriwan/AdashimaaTube/raw/master/AdashimaaTube.user.css)

**Comment by Youtubepls** [comment]
Thanks so far. It works for the video titles, but the font size of the view count and the upload date still is bigger than usual:

![bigger font 3](https://user-images.githubusercontent.com/127688486/224671998-fced2fa0-19ba-46b4-9474-34ebd04f2279.PNG)

Could you have another look? Sorry for the trouble btw^^
