### ISSUE TITLE
The Comment Button Issue (Does not need immediate fix since it doesn't ruin the viewing experience lol and the button still works, just a visual issue)

### ISSUE THREAD

**Issue by SamGitHub1807** [sapondanaisriwan/AdashimaaTube#49]
Hey, Sam again! It's been a while, but I'm still here lol! I'm not sure what to title this issue or how to explain, so I'll be using images

Before typing something:
<img width="1046" alt="Screenshot 2023-03-13 at 08 19 41" src="https://user-images.githubusercontent.com/122677421/224583208-63d79c37-a399-4f5b-afa3-4252165e66c2.png">

After typing something:
<img width="1038" alt="Screenshot 2023-03-13 at 08 19 14" src="https://user-images.githubusercontent.com/122677421/224583181-d9bc9b53-36dd-4dd5-b4ca-66338c4f626e.png">

**Comment by sapondanaisriwan** [comment]
v2.0.5 is worst 😂
Expected:
![vJlRnDis4j](https://user-images.githubusercontent.com/64634605/224618307-2e8c5fee-29e4-4da1-9797-1485c8234c77.png)

**Comment by SamGitHub1807** [comment]
Thank you! ❤️

**Comment by sapondanaisriwan** [comment]
No problem😊
