### ISSUE TITLE
RTD Compatibility?

### ISSUE THREAD

**Issue by KingGamingYT** [sapondanaisriwan/AdashimaaTube#52]
I haven’t seen an issue about this, so will return youtube dislike compatibility be added in the future? As of now, if you have the extension installed the count will simply be hidden by the userstyle.

**Comment by sapondanaisriwan** [comment]
what do you mean? it still works for me.
![msedge_i1OvAjuVKv](https://user-images.githubusercontent.com/64634605/224774689-8a42eefe-b349-4045-9b34-3eb595ca7fd8.png)

**Comment by KingGamingYT** [comment]
My mistake, it was a page issue, it fixed itself when I reloaded. Closing now.
