### ISSUE TITLE
Hide buttons reappearing even though they are suppose to be hidden 

### ISSUE THREAD

**Issue by Bottomfard6127** [sapondanaisriwan/AdashimaaTube#55]
Hello mate, back again with another bug report, so the option of removing the thanks, and clip button is kinda broken right now, when I click on a video supporting those options they still appear even though I have them on, they do disappear when I turn off and on the script but when I click out of the video and then rewatch, they appear again, even though I have them turned off, I haven't tested the other options of removing buttons or if this is a me problem too
![image](https://user-images.githubusercontent.com/126884197/224989828-1c570835-8b4d-424b-8127-3a4f88f904ea.png)

Edit: Also when I refresh the site after I reapply the script to remove the buttons they appear again

**Comment by sapondanaisriwan** [comment]
weird, it's still working for me.
![msedge_EJISYFB3ll](https://user-images.githubusercontent.com/64634605/224991186-05afc06b-21ff-4f4b-8ae3-6905bfdd2c76.png)

**Comment by Bottomfard6127** [comment]
maybe its a me thing again, I'll test it on different accounts and browsers

**Comment by Bottomfard6127** [comment]
maybe because I have delete all cookies for youtube when I use firefox because it seem it seems fine on other browsers like opera gx

**Comment by Bottomfard6127** [comment]
yeah I restarted my firefox and the issue still pesists even when I made youtube as an exception for delete all cookies, but it works fine on other browsers though

**Comment by sapondanaisriwan** [comment]
Have you ever done these [steps](https://github.com/sapondanaisriwan/AdashimaaTube#-installation)?
![image](https://user-images.githubusercontent.com/64634605/225000063-3333fe15-35da-42b6-abf5-f31f25b2c60b.png)

**Comment by Bottomfard6127** [comment]
yeah I did a long time ago

![image](https://user-images.githubusercontent.com/126884197/225002441-737bc73b-a21e-4dbb-837e-e96daeb82016.png)

**Comment by sapondanaisriwan** [comment]
I think the problem is Firefox. Is it still working on your side?

**Comment by Bottomfard6127** [comment]
it is still working and yeah it eventually went ahead and got hidden it maybe just takes some time
