### ISSUE TITLE
YouTube has killed the elder Subscribe Button

### ISSUE THREAD

**Issue by KingGamingYT** [sapondanaisriwan/AdashimaaTube#58]
Tonight the older Subscribe button simply vanished, which means YouTube either hid it further or completely removed it.
![image](https://user-images.githubusercontent.com/45918062/225811517-3ad55c42-fa37-499b-86e1-ab41ddd007ea.png)

**Comment by KingGamingYT** [comment]
Update: they killed the SubscribeD button, the regular "Subscribe" button works fine until you click it, when it disappears.

**Comment by SamGitHub1807** [comment]
Yes, I have experienced this issue.

More issues: 

(When searching a channel, the subscribe button does not turn red. (I am currently signed in to my google account too)
<img width="197" alt="image" src="https://user-images.githubusercontent.com/122677421/225812129-5f278b33-0aef-4482-a0d6-9f235ad9ef6c.png">

(Same case for the watch page as well)
<img width="298" alt="image" src="https://user-images.githubusercontent.com/122677421/225812218-7ca294fd-e6ba-4c06-b77f-fc2998853bc2.png">

(Channel pages as well)
<img width="1054" alt="image" src="https://user-images.githubusercontent.com/122677421/225812293-0082ff47-8c6c-4fd0-a728-87a80bb0932c.png">

(Shorts as well)
<img width="169" alt="image" src="https://user-images.githubusercontent.com/122677421/225813262-523613ed-916b-4754-bd86-64e16c97a8e9.png">

That's all!

**Comment by sapondanaisriwan** [comment]
what a good news

**Comment by sapondanaisriwan** [comment]
please temporarily disable the old watch page. I'm not sure I can fix it maybe I need to rewrite everything again.
![G4LGqsItEV](https://user-images.githubusercontent.com/64634605/225819888-ecc9c599-00c4-45c8-a5f2-74cb02caf719.png)

**Comment by SamGitHub1807** [comment]
> what a good news

Apologies, I didn't mean it like that. I should have put it more gently, I know this will be a lot of work. 😓

**Comment by sapondanaisriwan** [comment]
> > what a good news
> 
> Apologies, I didn't mean it like that. I should have put it more gently, I know this will be a lot of work. 😓

you don't need to apologize anything. It's just a bad joke.

**Comment by sapondanaisriwan** [comment]
Subscribe button on the channels tap.
![msedge_wD4EBUv189](https://user-images.githubusercontent.com/64634605/225822980-bcd9fde0-6863-4faa-b079-508a18a836ee.png)

**Comment by SamGitHub1807** [comment]
Oh I didn't realize that, wow, wondering what YouTube have been doing

**Comment by sapondanaisriwan** [comment]
@SamGitHub1807 @KingGamingYT The bug was fixed. You can [update](https://github.com/sapondanaisriwan/AdashimaaTube#-how-to-update-adashimaatube-to-latest-version) to the latest version anytime.

**Comment by SamGitHub1807** [comment]
Thanks so much!

**Comment by sapondanaisriwan** [comment]
No problem :)
