### ISSUE TITLE
«Remove Chips» — not understood

### ISSUE THREAD

**Issue by IvanRussian15** [sapondanaisriwan/AdashimaaTube#6]
«Remove Chips» switch is not understood by users until you see it actually work. It would be better to rename it to «Remove Tabs» or «Hide Tabs».

**Comment by sapondanaisriwan** [comment]
I see. I don't know what does it should call so I named it randomly 🤣

**Comment by sapondanaisriwan** [comment]
Everything's all right now.
![image](https://user-images.githubusercontent.com/64634605/204813923-e4fa1043-e2b2-49af-9152-ef7e80d31f67.png)
