### ISSUE TITLE
Empty spaces on Homepage

### ISSUE THREAD

**Issue by sapondanaisriwan** [sapondanaisriwan/AdashimaaTube#60]
Although I have no idea how to resolve the empty spaces issue, I can come up with three methods.
1. Zoom out
2. Remove the shorts section that I used in current version.
3. Make the shorts section the upper section at all times.

I'll try method 3 in the next update. If you have any suggestion, please let me know.
![image](https://user-images.githubusercontent.com/64634605/225981198-0f3eb923-5ce7-4064-a49e-21d38b1c935c.png)

**Comment by utkarshgupta137** [comment]
It might be due to the shorts section. Try closing it.

**Comment by sapondanaisriwan** [comment]
I'm tired to fix everything with CSS so this is the alternative way.

https://github.com/sapondanaisriwan/youtube-videos-per-row-fix

![](https://imgur.com/9gszEVE)

```js
const target = "ytd-rich-grid-renderer";

customElements.whenDefined(target).then(() => {
  const proto = customElements.get(target).prototype;

  const waitUntilExits = () => {
    // call waitUntilExits again after 0ms until it exits
    if (!proto.calcElementsPerRow) return setTimeout(waitUntilExits, 0);

    // Set the value of calcElementsPerRow to 5
    proto.calcElementsPerRow = () => 5;
  };
  waitUntilExits();
});
```
