### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by shahin365** [sapondanaisriwan/AdashimaaTube#61]
Hi,
Can a feature be added to turn off the Annotations permanently from the style? right now if you toggle it off it only applies to the current video and youtube won't remember the change. 

![Annotations](https://user-images.githubusercontent.com/16749755/226012604-a1c369f2-b9e4-46ad-9913-d54f0be4fc83.png)

**Comment by sapondanaisriwan** [comment]
If it still appears please tell me

**Comment by shahin365** [comment]
> 

there is no update style hasn't changed since the request.

**Comment by shahin365** [comment]
> If it still appears please tell me


there is no update style hasn't changed since the request.

**Comment by sapondanaisriwan** [comment]
@shahin365  I'm going to release it in the next update. [Here you are](https://github.com/sapondanaisriwan/AdashimaaTube/raw/master/AdashimaaTube.user.css) if you want to test it.

**Comment by shahin365** [comment]
> @shahin365 I'm going to release it in the next update. [Here you are](https://github.com/sapondanaisriwan/AdashimaaTube/raw/master/AdashimaaTube.user.css) if you want to test it. ![msedge_41Y0Ieockf](https://user-images.githubusercontent.com/64634605/226094697-54d3af3c-f9e6-4a6b-9426-5c1923e0be27.png)

It works. Thanks!
