### ISSUE TITLE
Virus-like behavior of the style

### ISSUE THREAD

**Issue by IvanRussian15** [sapondanaisriwan/AdashimaaTube#62]
![изображение](https://user-images.githubusercontent.com/48278585/226074722-64dfa87c-c237-4518-a646-a22957b6470b.png)
There are neater ways to tell the user to update their browser. [Which, however, will not help Firefox users](https://developer.mozilla.org/en-US/docs/Web/CSS/:has#browser_compatibility)

**Comment by sapondanaisriwan** [comment]
I think so too. Can you give me an example to tell the Firefox user?

**Comment by DAOWAce** [comment]
When was this added?

I use a very old version of Chrome and haven't seen it, but I disabled updates of the addon a bit ago (1.8.5).

Though, now I see the description page has a 'legacy' version of the style, which is understandable. Will probably convert over to that since the new version was bugged a bit.

**Comment by sapondanaisriwan** [comment]
> When was this added?
> 
> I use a very old version of Chrome and haven't seen it, but I disabled updates of the addon a bit ago (1.8.5).
> 
> Though, now I see the description page has a 'legacy' version of the style, which is understandable. Will probably convert over to that since the new version was bugged a bit.

It was added since in [v2.0.0](https://github.com/sapondanaisriwan/AdashimaaTube/blob/master/CHANGELOG.md#v200)

**Comment by sapondanaisriwan** [comment]
![msedge_owKfd37sRJ](https://user-images.githubusercontent.com/64634605/226307634-de061ffb-cbf4-4c14-8bf0-921eda5de7bb.png)

**Comment by IdrisQe** [comment]
Given you have the ability to detect if this message needs to show, couldn't you instead just grey out the options that don't work without an update and put a small, unobtrusive message that says this?

I understand that's what the Legacy version is for, but I can say for sure I didn't appreciate the style literally hijacking any Youtube page when I updated it - I use Waterfox, its _latest_ version is based on FF102 ESR which doesn't have the ability to enable the "has" selector, so the information in this was useless to me.

I'd much rather just have some features auto-disabled than the ability to use Youtube at all stolen from me like some kind of malware.
