### ISSUE TITLE
Issue with Creator Support chat

### ISSUE THREAD

**Issue by Qr9Vt4Q2DAxv3I0Dh10CBOIHCTvU96KBcpLRLDm** [sapondanaisriwan/AdashimaaTube#63]
When you open a creator support chat in your YouTube studio the text goes very small. 

<img width="336" alt="Support Chat queue" src="https://user-images.githubusercontent.com/121949954/226161902-e7c057b2-2ea0-4a9e-86aa-309fa80159ac.png">
<img width="336" alt="Support Chat Conversation" src="https://user-images.githubusercontent.com/121949954/226161929-686671b9-7013-4108-8876-899df861a65b.png">

**Comment by sapondanaisriwan** [comment]
How can I open support chat?
![msedge_PBkgOfatRZ](https://user-images.githubusercontent.com/64634605/226162811-c8ca9f9f-da70-4cd2-be3a-9ce10a615cd7.png)

**Comment by Qr9Vt4Q2DAxv3I0Dh10CBOIHCTvU96KBcpLRLDm** [comment]
You have to be in YPP

**Comment by sapondanaisriwan** [comment]
what is YPP?

**Comment by sapondanaisriwan** [comment]
I think it caused by the custom font size, so I decided to remove it in [v2.1.1](/sapondanaisriwan/AdashimaaTube/raw/master/AdashimaaTube.user.css).

**Comment by Qr9Vt4Q2DAxv3I0Dh10CBOIHCTvU96KBcpLRLDm** [comment]
Issue has indeed been resolved, YPP is YouTube Partner Program/Monetisation
