### ISSUE TITLE
No sort buttons on channels

### ISSUE THREAD

**Issue by MrGoatsy** [sapondanaisriwan/AdashimaaTube#65]
See this image:
![image](https://user-images.githubusercontent.com/9994607/226275663-d94e1916-aba4-4ab5-9584-b8cd96903b5d.png)

I would like to be able to sort by popular and stuff if at all possible.

**Comment by sapondanaisriwan** [comment]
Just disable "Hide taps"
![BPfXwn3xmr](https://user-images.githubusercontent.com/64634605/226277571-b08db50e-eb52-470d-9d1a-99671eb94823.png)

**Comment by MrGoatsy** [comment]
That does nothing for me.

**Comment by sapondanaisriwan** [comment]
Can you
