### ISSUE TITLE
With the new "Always show progress bar" feature, the progress bar doesn't progress/move (I don't know if this is intentional or not lol. If it is, I'll just close this haha)

### ISSUE THREAD

**Issue by SamGitHub1807** [sapondanaisriwan/AdashimaaTube#66]
As you can see, I've enabled the new "Always show progress bar" feature that version 2.1.2 introduced. The issue is: the progress bar does not move/progress at all (unless hovering over the video). Hopefully this quick video will explain everything! 

(If this is intentional, or something that is unable to be fixed, I'll close this issue!)

https://user-images.githubusercontent.com/122677421/226318261-fd87c72d-6528-45c9-b050-607307fdb3e6.mov

That's all!

**Comment by sapondanaisriwan** [comment]
Lmao I thought it works perfectly (I forgot to test it before release)

**Comment by sapondanaisriwan** [comment]
It's not possible with just CSS. JavaScript would be required to fix this.

**Comment by sapondanaisriwan** [comment]
It's time to remove this feature 🤣

**Comment by SamGitHub1807** [comment]
Ahh okay, I understand! It's all good. Will close this now lol.

**Comment by sapondanaisriwan** [comment]
I'm sorry I forgot to test it lol

**Comment by SamGitHub1807** [comment]
No need for apologies haha, thanks for letting me know. It's understandable that things can slip through the cracks sometimes. Still happy that this update added 2 other convenient, useful and awesome features!
