### ISSUE TITLE
Manage subscriptions link is missing

### ISSUE THREAD

**Issue by KosMos-pv** [sapondanaisriwan/AdashimaaTube#67]
When I go to my subscriptions there is no such link on top right near buttons to switch layout. I tried to disable all options in style settings but nothing helps. If I disable this style completely link is back as expected.

**Comment by sapondanaisriwan** [comment]
On my end, it works perfectly. Can you send me a screenshot?
![msedge_56fRszd6WJ](https://user-images.githubusercontent.com/64634605/226921212-a816613d-0698-454a-9770-be11e811fcfe.png)

**Comment by sapondanaisriwan** [comment]
@KosMos-pv Try [update](https://github.com/sapondanaisriwan/AdashimaaTube#-how-to-update-adashimaatube-to-latest-version) to the latest version

**Comment by KosMos-pv** [comment]
Thanks, updated to latest version and problem is fixed now. I thought Stylus updates styles automatically.
