### ISSUE TITLE
livestream chat

### ISSUE THREAD

**Issue by Sniperexe** [sapondanaisriwan/AdashimaaTube#68]
It's nothing serious, it's just another youtube update that changed when clicking anywhere in the frame of the live chat it opens the menu which originally would open only by pressing the 3 dots next to the message.. kind of annoying when scrolling through the chat and mistakenly this small menu pops up. Obviously would like this change reverted in the future.

And another issue I'm having, is that the viewers count in a livestream doesn't automatically update, don't know if I'm the only one who's facing this but would like to let you know.

The screenshot below refers to my first concern
![Screenshot (95)](https://user-images.githubusercontent.com/97830738/227037224-8d8b7908-8eea-4f51-be33-59a7886f4427.png)

**Comment by sapondanaisriwan** [comment]
Unfortunately, the viewers count in a livestream can't be fix with just CSS (Require JS)

**Comment by Sniperexe** [comment]
k, I think from my end everything seems to work fine now so I'll proceed to close this ticket for our both convenience.

**Comment by Sniperexe** [comment]
Was I supposed to receive the dialog box in the screenshot embedded below? In case you're wodering, yes, I have your extension updated to the latest verion, however the livestream view count doesn't seem to refresh. I might as well provide you with a video getting the error mentioned before as well as the livestream view count remaining the same, if you require me to. Thanks though for looking into my case.
![error](https://user-images.githubusercontent.com/97830738/236254210-3992e3cf-e22f-417b-ae5f-b09ae2ea2260.PNG)
