### ISSUE TITLE
SaveFrom Helper Extension Support?

### ISSUE THREAD

**Issue by anar4732** [sapondanaisriwan/AdashimaaTube#69]
Hi. thank you for this project I hate the new layout and this feels like coming back home after a long trip.

SaveFrom Helper is an extension that adds a download button near the like-dislike buttons.

Can you add support so the button won't disappear when installing this?

https://chrome.google.com/webstore/detail/savefrom-helper/akncjgblpooaigmieecjiigaebgblnaj

**Comment by sapondanaisriwan** [comment]
AdashimaaTube is just userstyle so It's very normal that they can't be compatible with each other.  If you wish to use another script or extension with AdashimaaTube, please contact the author of that script.
