### ISSUE TITLE
Dismissed messages with rounded border

### ISSUE THREAD

**Issue by noobschoolbus** [sapondanaisriwan/AdashimaaTube#7]
Found an element that still has rounded borders. Dismissed messages on the home page.
![Clipboard01](https://user-images.githubusercontent.com/76540667/205465322-895ad0ec-cb46-48ec-acf4-42972531b97a.jpg)

I used ublock Origin to find the element name ###dismissed > .ytd-feed-nudge-renderer.style-scope
Adding this line fixed it for me:

    .ytd-feed-nudge-renderer.style-scope {
        border-radius: 0 !important;
    }

**Comment by noobschoolbus** [comment]
Looks like the same issue for selecting "not interested" or "do not recommend channel"
![Clipboard02](https://user-images.githubusercontent.com/76540667/205465590-599ee628-12f2-48b1-bf11-f2d66aceba58.jpg)

For this one I added

    .ytd-rich-grid-media.style-scope{
         border-radius: 0 !important;
    }

Looks much cleaner:
![Clipboard03](https://user-images.githubusercontent.com/76540667/205465610-fa436b50-e1c2-4b01-a49a-607a1d4c0153.jpg)

**Comment by sapondanaisriwan** [comment]
Fixed, You can update at any time to the most recent version with the some [bugs].(https://github.com/sapondanaisriwan/AdashimaaTube/blob/master/CHANGELOG.md#v148)
