### ISSUE TITLE
The color of the topbar on theater mode is black instead of dark grey.

### ISSUE THREAD

**Issue by Techfromthepast123** [sapondanaisriwan/AdashimaaTube#71]

**Comment by Techfromthepast123** [comment]
![Capture d'écran 2023-03-30 150918](https://user-images.githubusercontent.com/112059671/228846819-c4b59fd5-1610-4b22-b95a-dff861193b1c.png)

**Comment by Techfromthepast123** [comment]
In the old layout,the theater mode bar used the grey darkmode color instead of the current black one (couldnt find a screenshot of the old layout,s theater mode,this issue only happens in light mode).

**Comment by sapondanaisriwan** [comment]
Like this, right?
![msedge_QPk5csVNHS](https://user-images.githubusercontent.com/64634605/229266256-485a9220-e35f-4312-bf16-e8deefadc9cb.jpg)

**Comment by sapondanaisriwan** [comment]
If you're using uBlock add this filter instead `###masthead:remove-attr(dark)`. it would easier than using CSS to revert it back.

**Comment by Techfromthepast123** [comment]
No I meant the topbar used the brighter (grey) darkmode color and not the darker dark (black) color

**Comment by Techfromthepast123** [comment]
On theatre mode

**Comment by Techfromthepast123** [comment]
![Uploading 68747470733a2f2f692e696d6775722e636f6d2f466664315a46642e706e67.png…]()
Like this

**Comment by sapondanaisriwan** [comment]
Send the image again

**Comment by Techfromthepast123** [comment]
![maxresdefault](https://user-images.githubusercontent.com/112059671/229367207-94010edf-01c8-42c2-9237-ab30500b5cae.jpg)

**Comment by Techfromthepast123** [comment]
Here

**Comment by Techfromthepast123** [comment]
The theater mode topbar should have that color instead of the current black one

**Comment by sapondanaisriwan** [comment]
I'll fix it later

**Comment by sapondanaisriwan** [comment]
@Techfromthepast123 
![msedge_GWzn1kJfYm](https://user-images.githubusercontent.com/64634605/229683228-58a5b5c6-3e37-4c21-bad3-b09a37e1bd30.png)
