### ISSUE TITLE
Hide thanks clip not working

### ISSUE THREAD

**Issue by Trudeau566** [sapondanaisriwan/AdashimaaTube#73]
![Snipaste_2023-04-02_06-10-44](https://user-images.githubusercontent.com/118544592/229316334-175d227f-95fe-4b2d-9744-eb8aa3f4d4e9.png)

**Comment by Bottomfard6127** [comment]
Hello Trudeau566 I had a similar problem, I was able to fix it by just going full screen in and out, and then it will do as intended but it's a temporary fix.

**Comment by sapondanaisriwan** [comment]
What browser are you using? and what version of AdashimaaTube are you using?

**Comment by Trudeau566** [comment]
> 你使用的是什么浏览器？ 您使用的是什么版本的 AdashimaaTube？

edge
AdashimaaTube 2.14
It suddenly failed a few days ago

**Comment by SamGitHub1807** [comment]
This issue also happened to me before, but only the "CLIP" button was appearing even when disabled.

**Comment by sapondanaisriwan** [comment]
I can't help since I couldn't reproduce on my end. I guess is a bug of browser.

**Comment by Trudeau566** [comment]
2.1.8 version problem solved
