### ISSUE TITLE
Videos by rows settings doesn't work on the new subscription page layout..

### ISSUE THREAD

**Issue by jarredou** [sapondanaisriwan/AdashimaaTube#76]
I came here to use this plugin to fix the new subscription page layout, on recommandations by some reddit users.
Everything is working in the plugin, except the part I needed, the new subscription page with these new dumb large thumbnails (2 or 3 by rows) are still shown when it works on other pages (channels, home page...)

**Comment by sapondanaisriwan** [comment]
Can you provide me a screenshot? There have been no changes on my end.
![msedge_XRvSjCRinR](https://user-images.githubusercontent.com/64634605/231056971-0660952e-e4d4-44ae-802b-1cd7b2602a71.png)

**Comment by sapondanaisriwan** [comment]
I have not received any new updates from YouTube, so i can't help.
![image](https://user-images.githubusercontent.com/64634605/231367960-a02a0ba5-9f3a-44ac-a0b5-f35422c7c847.png)

**Comment by Ziko577** [comment]
I can confirm this. It started doing it to me today. The style works as intended on the rest of the site but this doesn't help me out in that regard. 
![No Changes](https://user-images.githubusercontent.com/6496151/232934857-5605671b-0e95-4ff1-a923-bb9b2bb23c18.jpg)

**Comment by sapondanaisriwan** [comment]
@Ziko577 @jarredou  I just got the UI changes in my alt account, so subscription page is now supported in [v2.1.8](https://github.com/sapondanaisriwan/AdashimaaTube#-how-to-update-adashimaatube-to-latest-version). If you found any bugs please create a new [issue](https://github.com/sapondanaisriwan/AdashimaaTube/issues/new).
![image](https://user-images.githubusercontent.com/64634605/233029813-eac4754e-c625-4e44-88fd-c5b1859326e9.png)
