### ISSUE TITLE
Youtube Miniplayer not really square

### ISSUE THREAD

**Issue by MossyMosMos** [sapondanaisriwan/AdashimaaTube#78]
i'd just notice that the black round space edge at miniplayer very recently, usually it should be filled a whole square with no round space edges left in it
<img width="332" alt="miniplayernotsquare" src="https://user-images.githubusercontent.com/126743138/231620133-5859732b-f93d-4cb8-b5ea-c71bb39a4353.png">

<img width="332" alt="miniplayernotsquarenotice" src="https://user-images.githubusercontent.com/126743138/231621246-fcfe1e13-93f0-4fc3-a911-bff31bbc3241.png">

<img width="332" alt="miniplayernotsquarenotice2" src="https://user-images.githubusercontent.com/126743138/231622499-085e67f4-f95e-4922-a8e3-a8b6dfa3a6b5.png">

i think maybe an another miniplayer ui update again....

**Comment by SamGitHub1807** [comment]
Oh! Also this.

<img width="233" alt="image" src="https://user-images.githubusercontent.com/122677421/231628852-b3d1e993-ea4b-45ef-984f-bde7c0663387.png">
<img width="206" alt="Screenshot 2023-04-13 at 10 11 02" src="https://user-images.githubusercontent.com/122677421/231628907-7ce3de08-da45-4602-b353-23641d38ec3f.png">

That's all
