### ISSUE TITLE
Unknown word / Videos per row not working

### ISSUE THREAD

**Issue by jochenwuerfel** [sapondanaisriwan/AdashimaaTube#79]
Hi,
installed the style but get this error:

![image](https://user-images.githubusercontent.com/101515602/232203196-d9db6020-9463-4310-b470-698c87d50792.png)

Maybe this is the issue why "videos per row" is not working.

Tested with the latest Chrome version and Stylus and Stylus (beta).

**Comment by sapondanaisriwan** [comment]
Try to disable CSS Linter
![msedge_Q2AmY19PqF](https://user-images.githubusercontent.com/64634605/232203773-62151d31-51da-4cfc-977a-cf893a3bee3d.png)

**Comment by jochenwuerfel** [comment]
Solves the error, unfortunately not the videos per row.

**Comment by sapondanaisriwan** [comment]
can you try to switch to another account?

**Comment by jochenwuerfel** [comment]
Tried, and noticed something as I don't have any subscriptions on the other account: it works for the main page but not for my subscription page: https://www.youtube.com/feed/subscriptions
Didn't noticed it in the first place as I look almost never anywhere else. Do I need to add this address somewhere?

**Comment by sapondanaisriwan** [comment]
The search page, home page, and channel page all support videos per row; however, the subscriptions page is still not supported because I haven't received any updates from YouTube.
https://github.com/sapondanaisriwan/AdashimaaTube/issues/76#issuecomment-1503970226

**Comment by jochenwuerfel** [comment]
Alright, bummer - but it's planned in case YouTube will answer you?

**Comment by sapondanaisriwan** [comment]
@jochenwuerfel I just got the UI changes in my alt account, so subscription page is now supported in [v2.1.8](https://github.com/sapondanaisriwan/AdashimaaTube#-how-to-update-adashimaatube-to-latest-version). If you found any bugs please create a new [issue](https://github.com/sapondanaisriwan/AdashimaaTube/issues/new).
![image](https://user-images.githubusercontent.com/64634605/233029813-eac4754e-c625-4e44-88fd-c5b1859326e9.png)
