### ISSUE TITLE
Error: 400, conflict with Improved Youtube?

### ISSUE THREAD

**Issue by DAOWAce** [sapondanaisriwan/AdashimaaTube#8]
This theme seems to expose a weird conflict with Improved Youtube.  https://github.com/code-for-charity/ImprovedTube-for-YouTube

![chrome_2022-12-04_10-05-49](https://user-images.githubusercontent.com/480587/205498390-0c56ce6e-de39-4cdf-831e-fbbd77ac3758.png)

These buttons appear here, along with that error 400 message.  Nothing I change in the 'details' settings in IY seems to affect them.

It's been this way since 1.3.1, and I originally didn't use the script because I found those buttons distracting, but now with the latest renamed one, it's still an issue, and searching the code, I don't see these anywhere in it, so it's something buried in the IY extension, and none of the active options I have do anything to affect it.

Is this conflict reproducible on your end?

**Comment by sapondanaisriwan** [comment]
I never receive a error 404 message, even though I enabled and disabled the ratiobar option.
![image](https://user-images.githubusercontent.com/64634605/205549648-b239c89b-d390-4d09-a0eb-5fef5cfa13e5.png)

**Comment by sapondanaisriwan** [comment]
I just recieved the error 404 message. You need to disabled "How long ago the video was uploaded" option (Go to Appearance > Detail > How long ago the video was uploaded)
![image](https://user-images.githubusercontent.com/64634605/205550913-abc6031b-1b56-4261-b068-c281d5953404.png)

**Comment by DAOWAce** [comment]
Oh that explains it; the option injects into the page but can't uninject, so it takes a reload to 'fix'.

Same with the 3 buttons I found annoying (which aren't in the appearance section, weirdly).

Thanks for getting to the root of this.  Time to go search the issues over there to see if other people have reported this weirdness (especially with the new YT layout hiding it).

**Comment by sapondanaisriwan** [comment]
Go to "Player" > "Scroll down to the bottom of the UI" to find these buttons, which you can disabled.
![image](https://user-images.githubusercontent.com/64634605/205761967-8d1adc43-09fe-4d8a-80d4-712224dfb1bc.png)
