### ISSUE TITLE
Channel page issue (Member "JOIN" button and colors)

### ISSUE THREAD

**Issue by SamGitHub1807** [sapondanaisriwan/AdashimaaTube#80]
Current:

<img width="1247" alt="image" src="https://user-images.githubusercontent.com/122677421/233258447-e66fc340-b616-4866-95a6-6e412e30a130.png">

Expected:
![image](https://user-images.githubusercontent.com/122677421/233258506-403f6592-21ad-42f9-8078-f61f8e01da52.png)
(Just the background colors needed)

![image](https://user-images.githubusercontent.com/122677421/233258655-214acaa2-83b8-408d-bc63-3d1e73fddb7d.png)

It also applies in the watchpage:
<img width="215" alt="image" src="https://user-images.githubusercontent.com/122677421/233258794-a5b3f8e2-d99c-4ea9-8a1e-7c92982c3cee.png">

That's all!

**Comment by sapondanaisriwan** [comment]
Hmm Did YouTube change the UI again?

**Comment by SamGitHub1807** [comment]
> Hmm Did YouTube change the UI again?

Oh, I'm not sur, nothing seems to have changed soo it's a little weird lol. But they have had a few watch page updates before!

**Comment by spodermenpls** [comment]
@sapondanaisriwan Thank you for maintaining this great Youtube userstyle, I appreciate your work a lot. Correct me if I'm mistaken, but I believe AdashimaaTube is missing an option to hide the "Join" (or "Mitglied werden"/"Become member" in my German locale) button:

![join-sponsor](https://github.com/sapondanaisriwan/AdashimaaTube/assets/23747593/19036aa0-d39e-48b2-a2b9-e35fd89b5b52)

As you can see, at least on my 15 inch screen, it's an annoyance and I wouldn't use this function anyway, so I am hiding it with the custom filter `www.youtube.com###sponsor-button` right now with uBlock Origin, however I'd prefer to be able to hide it with your userstyle right away, just like it's the case with the occasional "Thanks" button and Donation shelf already.
