### ISSUE TITLE
Buttons Radius setting not working

### ISSUE THREAD

**Issue by Sniperexe** [sapondanaisriwan/AdashimaaTube#84]
By adjusting the specific setting in your menu the buttons are supposed to have a square border respectively when hovering onto them, something that no longer works thanks to youtube's updated UI. A picture will be attached below in regards to this issue. 
People never but never liked youtube's changes in the UI throughout the years. They always complain until they got used to them and I was one of them, until I found this blessed extension. Whether it's nostalgia or not I personally believe they make it look uglier update by update.
Be sure to include a fix for this issue along with your next update, thanks.
![Screenshot (114)](https://user-images.githubusercontent.com/97830738/234103711-107ed68f-f030-4a9a-9184-c6eb368f8409.png)
![Screenshot (113)](https://user-images.githubusercontent.com/97830738/234103716-a1b8017c-7ea2-4aff-a1cf-4554b1221bd5.png)

**Comment by SamGitHub1807** [comment]
Oh, just a little something, I didn't remember, so I couldn't do this sooner and I apologize :(

It's just the taps roundness

<img width="338" alt="image" src="https://user-images.githubusercontent.com/122677421/234189709-8578eef8-6e0f-4c7e-9947-38ff476ddd54.png">

Expected:

<img width="541" alt="Screenshot 2023-04-25 at 14 15 13" src="https://user-images.githubusercontent.com/122677421/234189981-ace9788d-0dc0-459b-8d82-749543c9cf39.png">

**Comment by sapondanaisriwan** [comment]
> Oh, just a little something, I didn't remember, so I couldn't do this sooner and I apologize :(
> 
> It's just the taps roundness
> 
> <img alt="image" width="338" src="https://user-images.githubusercontent.com/122677421/234189709-8578eef8-6e0f-4c7e-9947-38ff476ddd54.png">
> 
> Expected:
> 
> <img alt="Screenshot 2023-04-25 at 14 15 13" width="541" src="https://user-images.githubusercontent.com/122677421/234189981-ace9788d-0dc0-459b-8d82-749543c9cf39.png">

Fixed 357fd95552649dc4c5d1b028e231085e008cc591

**Comment by SamGitHub1807** [comment]
Thank you! 🩵
