### ISSUE TITLE
Old icons + premium account

### ISSUE THREAD

**Issue by sapondanaisriwan** [sapondanaisriwan/AdashimaaTube#85]
Old icons not working if you're using premium account (IDK why). 
![msedge_dswh0R5Sm6](https://user-images.githubusercontent.com/64634605/235072649-e78ed09b-6836-4d77-891c-2bd48294f3f3.png)

![msedge_Sy2ktK6alO](https://user-images.githubusercontent.com/64634605/234284377-c606d2a3-1ea1-4b77-8986-9d873ca14e39.png)

Expected:
![image](https://user-images.githubusercontent.com/64634605/234284428-486b85c6-06cb-421f-a013-c0a8fb13e377.png)

I'm too lazy to fix this 🦥

**Comment by Techfromthepast123** [comment]
The reason the old icons dont work is due to a YouTube update that change the way icons work.
Its also not working on mine.

**Comment by sapondanaisriwan** [comment]
> The reason the old icons dont work is due to a YouTube update that change the way icons work. Its also not working on mine.

I'm going to remove this feature soon because it's very pain for me to revert it back using only CSS.

**Comment by Sniperexe** [comment]
also if you could add an option to remove the originals button, would be much appreciated
*may not appear to non-yt-premium-users

![4](https://github.com/sapondanaisriwan/AdashimaaTube/assets/97830738/695b2fe8-d423-4126-bbcc-c7436c342f92)

**Comment by sapondanaisriwan** [comment]
Fixed in version 2.2.7.  I'm not sure if it works with premium accounts or not.
