### ISSUE TITLE
Like Colors

### ISSUE THREAD

**Issue by Zycelz** [sapondanaisriwan/AdashimaaTube#89]
![image](https://user-images.githubusercontent.com/105969023/235288047-c5e37c6e-cba6-4524-a0b5-aaced60cb47f.png)
![image](https://user-images.githubusercontent.com/105969023/235288051-665f1511-82c8-44b5-b864-b17b2cfefd18.png)
not blue

**Comment by SamGitHub1807** [comment]
Solution:

Make sure that the "Youtube Appearance toggle is set to "Enabled" and not "Disabled".
<img width="209" alt="235294052-534bf6bc-58ec-4921-a632-11576d6507ee" src="https://user-images.githubusercontent.com/122677421/235294094-3f5ba2a1-3a83-4d0a-a328-a5c396abe64c.png">

<img width="227" alt="Screenshot 2023-04-29 at 16 53 36" src="https://user-images.githubusercontent.com/122677421/235294140-450133a8-e439-4485-a571-b7b83e4d2a0e.png">

And it should work now.

Light mode
<img width="151" alt="Screenshot 2023-04-29 at 16 53 57" src="https://user-images.githubusercontent.com/122677421/235294151-ca1efeb1-b37f-456e-a96f-cb0158bbc894.png">

Dark mode
<img width="173" alt="Screenshot 2023-04-29 at 16 54 07" src="https://user-images.githubusercontent.com/122677421/235294157-f39716b6-6e1b-42b2-baed-fe4763608769.png">

If it doesn't, try updating to the latest version of AdashimaaTube! If it still doesn't, then I'm not sure why.
