### ISSUE TITLE
[Bug]: (Visual Bugs) Two Visual Bugs have emerged!

### ISSUE THREAD

**Issue by SamGitHub1807** [sapondanaisriwan/AdashimaaTube#92]
### Describe the bug

The buttons "SUBSCRIBED and JOIN" (if a channel has a membership), as well as the "NOTIFICATION BELL" are misplaced, and the colors of these buttons in the side when you minimize (I'm not sure of the name lol).

### Screenshots

* The buttons "SUBSCRIBED and JOIN" (if a channel has a membership), as well as the "NOTIFICATION BELL" are misplaced.

EDIT: You can only see this when you subscribe to a channel.

As of my current knowledge, this applies in the:

- Channel page
- Watch page
- Search page

<img width="1249" alt="image" src="https://user-images.githubusercontent.com/122677421/236362129-8e7603ee-97a9-451c-9c22-269c9c0bdea8.png">

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/122677421/236362289-f075ab8b-3a9e-4493-bb13-a77796a1a8db.png">

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/122677421/236362251-97ce3242-bd2b-4861-bf54-1457ef56bfcb.png">

* The colors of these buttons in the side when you minimize. 

Before minimizing:
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/122677421/236362412-c9acff67-93a1-4a21-9248-263609aaa4d5.png">

After minimizing:

![image](https://user-images.githubusercontent.com/122677421/236362447-66ecb9c5-c3e9-42a0-ba0b-2c17f65de4d5.png)

Expected:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/122677421/236362478-37e741ab-da56-45fe-a8a2-bebd180d250e.png">

### What browser are you using?

Brave Version 1.51.110 Chromium: 113.0.5672.77 (Official Build (arm64)

### What version of AdashimaaTube are you using?

v2.2.1

**Comment by sapondanaisriwan** [comment]
again??
![image](https://user-images.githubusercontent.com/64634605/236369579-1d37629f-4291-462a-85e8-1582b2d62504.png)

**Comment by SamGitHub1807** [comment]
🤣 yep, and I'm gonna be honest, most of the UI changes ARE HORRIBLE
![image](https://user-images.githubusercontent.com/122677421/236369738-7316d24f-7f18-4875-b189-047bc4e2226b.png)

**Comment by sapondanaisriwan** [comment]
> 🤣 yep, and I'm gonna be honest, most of the UI changes ARE HORRIBLE ![image](https://user-images.githubusercontent.com/122677421/236369738-7316d24f-7f18-4875-b189-047bc4e2226b.png)

omg that's the worst UI forever.

**Comment by SamGitHub1807** [comment]
Thank you, so much! :D
