### ISSUE TITLE
[Bug]: Misaligned icons and channel name in youtube player 

### ISSUE THREAD

**Issue by Bottomfard6127** [sapondanaisriwan/AdashimaaTube#93]
### Describe the bug

Channel Names are misaligned from their channel profiles in youtube players and the subscribe button, join membership, and bell icon is misaligned. 

### Screenshots

![image](https://user-images.githubusercontent.com/126884197/236389054-c99f2798-7ba7-496d-9d45-90328be171d0.png)

### What browser are you using?

Firefox 112.0.2 (64-bit) official build

### What version of AdashimaaTube are you using?

v 2.2.1

**Comment by Bottomfard6127** [comment]
Also I forgot to add that it also affects the channel page too 

![image](https://user-images.githubusercontent.com/126884197/236389367-62d00113-f4cf-4745-b210-2a04e77c0228.png)

**Comment by sapondanaisriwan** [comment]
Duplicate https://github.com/sapondanaisriwan/AdashimaaTube/issues/92

**Comment by sapondanaisriwan** [comment]
it was fixed in [v2.2.2](https://github.com/sapondanaisriwan/AdashimaaTube#-how-to-update-adashimaatube-to-latest-version).

**Comment by Bottomfard6127** [comment]
> Duplicate #92

Oh I didn't notice sorry thanks for the tip!
