### ISSUE TITLE
[Feature request]: Option to hide recommended videos at the bottom of playlists

### ISSUE THREAD

**Issue by viktorkkost** [sapondanaisriwan/AdashimaaTube#94]
### Describe the change you'd like

They recently added a section under every playlist you own, recommending you to add videos in it. It would be nice to be able to hide it altogether as it's sometimes confusing when you scroll all the way down and see videos that aren't actually part of the playlist.

### Additional context
Screenshot of said section:
![recommended](https://user-images.githubusercontent.com/92181430/236693551-6f5ca08d-9a1d-4571-80f2-890b6a8ab5b8.jpg)

**Comment by sapondanaisriwan** [comment]
@viktorkkost  I added it already, you can install the changes from [here](https://github.com/sapondanaisriwan/AdashimaaTube/raw/master/AdashimaaTube.user.css)

![q3fZKnZonj](https://user-images.githubusercontent.com/64634605/236877027-566fe3c3-f7a2-4883-b0c5-8e3ef3883b8c.png)
