### ISSUE TITLE
[Bug]: Version 2.2.5 

### ISSUE THREAD

**Issue by shahin365** [sapondanaisriwan/AdashimaaTube#98]
### Describe the bug

Hi, I use this Chrome extension https://chrome.google.com/webstore/detail/youtube-tags/fffiogeaioiinfekkflcfebaoiohkkgp to see the video tags and the new 2.2.5 version messed it up (it's overlapping with the view count and date) 

### Screenshots

![x](https://github.com/sapondanaisriwan/AdashimaaTube/assets/16749755/9f8cc34e-156c-4448-8da7-9147b36e4fee)

### What browser are you using?

**Google Chrome Version 113.0.5672.92 and Firefox Version 113.0** 

### What version of AdashimaaTube are you using?

**v2.2.5**

**Comment by MossyMosMos** [comment]
also mine is even more buggy now
<img width="600" alt="yttitlebugged" src="https://github.com/sapondanaisriwan/AdashimaaTube/assets/126743138/132a0514-f2c0-4fed-b6b1-64f65d00bd80">
<img width="948" alt="yttitlebug" src="https://github.com/sapondanaisriwan/AdashimaaTube/assets/126743138/f421e7f2-4183-437a-be2c-2358f9e9c9ce">

video's title names and like/dislikes buttons are gone.

**Comment by sapondanaisriwan** [comment]
> also mine is even more buggy now <img alt="yttitlebugged" width="600" src="https://user-images.githubusercontent.com/126743138/237410921-132a0514-f2c0-4fed-b6b1-64f65d00bd80.png"> <img alt="yttitlebug" width="948" src="https://user-images.githubusercontent.com/126743138/237410957-f421e7f2-4183-437a-be2c-2358f9e9c9ce.png">
> 
> video's title names and like/dislikes buttons are gone.

Try to turn off other styles.
![msedge_PTGeCwfHyr](https://github.com/sapondanaisriwan/AdashimaaTube/assets/64634605/ab34150d-83fe-471a-8173-0db8c12ee8bd)

**Comment by MossyMosMos** [comment]
umm... if i tried to turn off other styles, maybe it's nothing change to it.

**Comment by Sniperexe** [comment]
1) Bug with game cards
![g](https://github.com/sapondanaisriwan/AdashimaaTube/assets/97830738/3c7182d9-94c8-49ee-b719-badac779cb9f)

2) I dont have OCD or anything but these options are supposed to be shorter
![g3](https://github.com/sapondanaisriwan/AdashimaaTube/assets/97830738/09c43bc5-783a-40ee-88fe-35d597057cc9)

**Comment by sapondanaisriwan** [comment]
> 1. Bug with game cards
>    ![g](https://user-images.githubusercontent.com/97830738/237452300-3c7182d9-94c8-49ee-b719-badac779cb9f.PNG)
> 2. I dont have OCD or anything but these options are supposed to be shorter
>    ![g3](https://user-images.githubusercontent.com/97830738/237452310-09c43bc5-783a-40ee-88fe-35d597057cc9.PNG)
> 
> Totally fucking hate youtube's consistent update of their UI

Can you send me the link of vidoe?

**Comment by sapondanaisriwan** [comment]
You can increase the width of popup.
![firefox_vphbyUPTiR](https://github.com/sapondanaisriwan/AdashimaaTube/assets/64634605/1ea08251-c299-4044-b21a-0be25d9427e5)

**Comment by Sniperexe** [comment]
> 

https://youtu.be/3fNc_dAvr7E

**Comment by Sniperexe** [comment]
another one is https://www.youtube.com/watch?v=tQDCQerjXFA&t=7s&ab_channel=Germanosgr
![g6](https://github.com/sapondanaisriwan/AdashimaaTube/assets/97830738/cf302417-2fb3-4b68-a8f5-14c4cf18be71)
Latest version of your extension, chrome updated and no additional styles in use.

**Comment by sapondanaisriwan** [comment]
I just release v2.2.6 if you still found the problem please let me know

**Comment by Sniperexe** [comment]
Everything seems to be working fine, thanks

**Comment by sapondanaisriwan** [comment]
No problem :)

**Comment by sapondanaisriwan** [comment]
Oh, I almost forgot to mention that I have no idea make it compatible with YouTube Tags extension.

**Comment by Sniperexe** [comment]
I can cope with it for the time being, unless they make anything stupid with it

**Comment by MossyMosMos** [comment]
after i updated style into v2.2.6 mine still have a title name display bug like before
<img width="576" alt="yttitlestillbuged" src="https://github.com/sapondanaisriwan/AdashimaaTube/assets/126743138/346f167b-44ca-4855-81c7-fc36f771cee6">

**Comment by sapondanaisriwan** [comment]
> > I just release v2.2.6 if you still found the problem please let me know
> 
> after i updated style into v2.2.6 mine still have a title name display bug like before :/
> <img width="576" alt="yttitlestillbuged" src="https://github.com/sapondanaisriwan/AdashimaaTube/assets/126743138/346f167b-44ca-4855-81c7-fc36f771cee6">
> 

Did you try what I said? Try to disable other styles

**Comment by MossyMosMos** [comment]
when i tried to toggled (unticked) into disabled the style , the title name and likes buttons etc. displays are returned somehow. but i'm gonna missed out from this beloved style. hope this able to fix in next updates.

**Comment by sapondanaisriwan** [comment]
> when i tried to toggled (unticked) into disabled this style , the title name and likes buttons etc. displays are returned somehow. but i'm gonna missed out from this beloved style. hope this able to fix in next updates.
> 
> when this style got disabled + (no other styles are used)
> 
> <img alt="ytstyledisabled" width="948" src="https://user-images.githubusercontent.com/126743138/237550471-1b5ea1d2-87cd-4650-8437-a7596e5bf8be.png">

If you don't use Return YouTube Dislike, I suggest using the original version [2.2.3](https://raw.githubusercontent.com/sapondanaisriwan/AdashimaaTube/master/archive/v2.2.3.user.css) before the changes.

**Comment by MossyMosMos** [comment]
> If you don't use Return YouTube Dislike, I suggest using the original version [2.2.3](https://raw.githubusercontent.com/sapondanaisriwan/AdashimaaTube/master/archive/v2.2.3.user.css) before the changes.

but how could i revert back into older version like you said? i'm gonna try that.

**Comment by Sniperexe** [comment]
I have exported about 7 versions of this style, so presumably I can help you out

**Comment by MossyMosMos** [comment]
> I have exported about 7 versions of this style, so presumably I can help you out if you want

i'm still thinking that how could i revert into previous version of styles

**Comment by Sniperexe** [comment]
It's not difficult, watch how below and you can see that every version has a relatively different menu of the extension. Regarding the file, I can send it to you.
https://youtu.be/DSo8gQKetww

**Comment by MossyMosMos** [comment]
i couldn't find the json files for previous versions. i'm looking for v2.2.3

**Comment by sapondanaisriwan** [comment]
> i couldn't find the json files for previous versions. i'm looking for v2.2.3

The easiest way is go to Achieve folder and find v2.2.3 then copy and paste in the editor. I can't record right now, I'm outside

**Comment by MossyMosMos** [comment]
> I could do it for ya
then how could i do it?

**Comment by Sniperexe** [comment]
@sapondanaisriwan may you confirm the steps?
https://youtu.be/Dkr1rkSu6U4

**Comment by shahin365** [comment]
> also mine is even more buggy now <img alt="yttitlebugged" width="600" src="https://user-images.githubusercontent.com/126743138/237410921-132a0514-f2c0-4fed-b6b1-64f65d00bd80.png"> <img alt="yttitlebug" width="948" src="https://user-images.githubusercontent.com/126743138/237410957-f421e7f2-4183-437a-be2c-2358f9e9c9ce.png">
> 
> video's title names and like/dislikes buttons are gone.
> 
> do i need to add that extension to display video title name?

I don't understand why you wouldn't open your own ticket for your issue? all these replies have nothing to do with the issue mentioned in the original post.
